//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CAN_BOA.rc
//
#define IDC_BUT_REMOVE                  3
#define IDC_BUT_SELECT                  5
#define IDD_PPAGE_CONTROLLER            107
#define IDD_DLG_HW_LISTING              130
#define IDD_DLG_ACCEPTANCE              197
#define IDR_BMP_NET                     204
#define IDC_EDIT_BAUD_RATE              1000
#define IDC_EDIT_NET_NAME               1007
#define IDC_EDIT_FIRMWARE               1008
#define IDC_STAT_BAUD_RATE              1013
#define IDC_STAT_KBPS                   1014
#define IDC_STAT_BUAD_RATE              1015
#define IDC_STAT_BUAD_RATE2             1016
#define IDC_LSTC_HW_LIST                1018
#define IDC_EDIT_DRIVER_ID              1019
#define IDC_COMB_SAMPLING               1019
#define IDC_BUT_BLINK                   1020
#define IDC_COMB_SJW                    1023
#define IDC_COMB_BTL                    1024
#define IDC_ButtonOK                    1060
#define IDC_STAT_LINE3                  1119
#define IDC_EDIT_WARNING_LIMIT          1175
#define IDC_EDIT_ACCEPTANCE_CODE2       1181
#define IDC_CBTN_ACCETANCE_OK           1200
#define IDC_EDIT_ACCEPTANCE_MASK2       1201
#define IDC_EDIT_ACCEPTANCE_CODE3       1202
#define IDC_EDIT_ACCEPTANCE_MASK3       1203
#define IDC_EDIT_ACCEPTANCE_MASK1       1204
#define IDC_EDIT_ACCEPTANCE_MASK4       1205
#define IDC_EDIT_ACCEPTANCE_CODE1       1206
#define IDC_EDIT_ACCEPTANCE_CODE4       1207
#define IDC_RBTN_SINGLE_FILTER_MODE     1208
#define IDC_RBTN_DUAL_FILTER_MODE       1209
#define IDC_STAT_FILTER_MODE            1210
#define IDC_STAT_ACCEPTANCE_FILTER_CODE 1211
#define IDC_STAT_ACCEPTANCE_FILTER_MASK 1212
#define IDC_LSTC_SELECTED_HW_LIST       1226
#define IDC_LIST_CHANNELS               1246
#define IDD_CONFIG_STUB                 3000
#define IDC_EDIT_INITFILE               3001
#define IDD_LIST_HW_INTRS               3002
#define IDC_BUTTON1                     3002
#define IDC_BUTTON_APPLY                3003
#define IDC_LIST1                       3004
#define IDD_DLG_CHANGE_REGISTERS_CAN_ETAS_BOA 3004
#define IDC_NAME                        3005
#define IDC_VENDOR                      3006
#define IDC_DESC                        3007
#define IDR_PGM_EDTYPE                  3007
#define IDC_CHECK_SELF_REC              3010
#define IDC_COMB_SAMPOINT               3011
#define IDC_EDIT_CHANNEL_DESC           3012
