//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch FLEXRAY_GIGATRONIK_FLEXI.rc
//
#define ID_SEPARATOR                    0
#define IMAGE_BITMAP                    0
#define ICM_NOTOPEN                     0x0000
#define EPR_0                           0
#define CTFMODEBIAS_DEFAULT             0x0000
#define EMO_EXIT                        0
#define EMO_EXPANDSELECTION             0
#define ENM_NONE                        0x00000000
#define ES_EX_NOCALLOLEINIT             0x00000000
#define CFU_UNDERLINENONE               0
#define SCF_DEFAULT                     0x0000
#define PFNS_PAREN                      0x000
#define SEL_EMPTY                       0x0000
#define ST_DEFAULT                      0
#define GT_DEFAULT                      0
#define GTL_DEFAULT                     0
#define _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE 0
#define SEEK_SET                        0
#define _IOFBF                          0x0000
#define ICONV_TRIVIALP                  0
#define EXIT_SUCCESS                    0
#define _OUT_TO_DEFAULT                 0
#define defPEAK_USB_SIM_HW_HANDLE       0
#define defINIT_CODE_VALUE              0x00
#define defERR_OK                       0
#define VS_VERSION_INFO                 1
#define SES_EMULATESYSEDIT              1
#define IMF_AUTOKEYBOARD                0x0001
#define ICM_LEVEL3                      0x0001
#define TO_ADVANCEDTYPOGRAPHY           1
#define EPR_270                         1
#define CTFMODEBIAS_FILENAME            0x0001
#define IMF_SMODE_PLAURALCLAUSE         0x0001
#define ICT_RESULTREADSTR               1
#define EMO_ENTER                       1
#define EMO_EXPANDDOCUMENT              1
#define ENM_CHANGE                      0x00000001
#define ECO_AUTOWORDSELECTION           0x00000001
#define ECOOP_SET                       0x0001
#define PC_FOLLOWING                    1
#define IMF_FORCENONE                   0x0001
#define CFM_BOLD                        0x00000001
#define CFE_BOLD                        0x0001
#define CFU_UNDERLINE                   1
#define SCF_SELECTION                   0x0001
#define SF_TEXT                         0x0001
#define PFM_STARTINDENT                 0x00000001
#define PFN_BULLET                      1
#define PFA_LEFT                        1
#define SEL_TEXT                        0x0001
#define OLEOP_DOVERB                    1
#define ST_KEEPUNDO                     1
#define GT_USECRLF                      1
#define GTL_USECRLF                     1
#define __STDC_WANT_SECURE_LIB__        1
#define _CRT_BUILD_DESKTOP_APP          1
#define SEEK_CUR                        1
#define _IOREAD                         0x0001
#define _TWO_DIGIT_EXPONENT             0x1
#define EPERM                           1
#define ICONV_GET_TRANSLITERATE         1
#define EXIT_FAILURE                    1
#define _OUT_TO_STDERR                  1
#define _WRITE_ABORT_MSG                0x1
#define TX_FLAG                         0x01
#define LIN_PID_LENGTH                  1
#define LIN_CHECKSUM_LENGTH             1
#define LIN_CHANNEL_1                   1
//#define defUSB_MODE_ACTIVE              1
//#define defMODE_ACTIVE                  1
//#define defCONTROLLER_ACTIVE            1
#define defSamplingVal                  1
#define SES_BEEPONMAXTEXT               2
#define IMF_AUTOFONT                    0x0002
#define ICM_LEVEL2                      0x0002
#define TO_SIMPLELINEBREAK              2
#define EPR_180                         2
#define CTFMODEBIAS_NAME                0x0002
#define IMF_SMODE_NONE                  0x0002
#define EMO_PROMOTE                     2
#define VM_OUTLINE                      2
#define ENM_UPDATE                      0x00000002
#define ECOOP_OR                        0x0002
#define PC_LEADING                      2
#define IMF_FORCEENABLE                 0x0002
#define CFM_ITALIC                      0x00000002
#define CFE_ITALIC                      0x0002
#define CFU_UNDERLINEWORD               2
#define SCF_WORD                        0x0002
#define SF_RTF                          0x0002
#define PFM_RIGHTINDENT                 0x00000002
#define PFN_ARABIC                      2
#define PFA_RIGHT                       2
#define SEL_OBJECT                      0x0002
#define ST_SELECTION                    2
#define GT_SELECTION                    2
#define GTL_PRECISE                     2
#define SEEK_END                        2
#define _IOWRT                          0x0002
#define XML_DETECT_IDS                  2
#define ENOENT                          2
#define ICONV_SET_TRANSLITERATE         2
#define _OUT_TO_MSGBOX                  2
#define _CALL_REPORTFAULT               0x2
#define RX_FLAG                         0x02
//#define defUSB_MODE_PASSIVE             2
//#define defMODE_PASSIVE                 2
//#define defCONTROLLER_PASSIVE           2
#define ICM_LEVEL2_5                    0x0003
#define EPR_90                          3
#define CTFMODEBIAS_READING             0x0003
#define EMO_EXPAND                      3
#define ECOOP_AND                       0x0003
#define WB_CLASSIFY                     3
#define PC_OVERFLOW                     3
#define CFU_UNDERLINEDOUBLE             3
#define SF_RTFNOOBJS                    0x0003
#define PFN_LCLETTER                    3
#define PFA_CENTER                      3
#define ESRCH                           3
#define ICONV_GET_DISCARD_ILSEQ         3
#define _MAX_DRIVE                      3
#define _REPORT_ERRMODE                 3
#define LENGTH_STR_DLC_CAN              3
#define LENGTH_STR_DLC_LIN              3
//#define defUSB_MODE_SIMULATE            3
//#define defMODE_SIMULATE                3
//#define defCONTROLLER_BUSOFF            3
#define IDC_BUT_REMOVE                  3
#define SES_EXTENDBACKCOLOR             4
#define IMF_IMECANCELCOMPLETE           0x0004
#define ICM_LEVEL2_SUI                  0x0004
#define TO_DISABLECUSTOMTEXTOUT         4
#define CTFMODEBIAS_DATETIME            0x0004
#define EMO_MOVESELECTION               4
#define VM_NORMAL                       4
#define ENM_SCROLL                      0x00000004
#define ECOOP_XOR                       0x0004
#define WB_MOVEWORDLEFT                 4
#define WB_MOVEWORDPREV                 4
#define PC_DELIMITER                    4
#define IMF_FORCEDISABLE                0x0004
#define CFM_UNDERLINE                   0x00000004
#define CFE_UNDERLINE                   0x0004
#define CFU_UNDERLINEDOTTED             4
#define SCF_ALL                         0x0004
#define SF_TEXTIZED                     0x0004
#define PFM_OFFSET                      0x00000004
#define PFN_UCLETTER                    4
#define PFA_JUSTIFY                     4
#define PFA_FULL_INTERWORD              4
#define SEL_MULTICHAR                   0x0004
#define ST_NEWCHARS                     4
#define GT_RAWTEXT                      4
#define GTL_CLOSE                       4
#define BOM_NEUTRALOVERRIDE             0x0004
#define BOE_NEUTRALOVERRIDE             0x0004
#define _IONBF                          0x0004
#define XML_COMPLETE_ATTRS              4
#define EINTR                           4
#define ICONV_SET_DISCARD_ILSEQ         4
#define ERR_FLAG                        0x04
#define LENGTH_STR_CHANNEL_CAN          4
#define LENGTH_STR_DIRECTION_CAN        4
#define LENGTH_STR_CHANNEL_LIN          4
#define LENGTH_STR_DIRECTION_LIN        4
#define ICM_CTF                         0x0005
#define CTFMODEBIAS_CONVERSATION        0x0005
#define EMO_GETVIEWMODE                 5
#define WB_MOVEWORDRIGHT                5
#define WB_MOVEWORDNEXT                 5
#define CFU_UNDERLINEDASH               5
#define PFN_LCROMAN                     5
#define PFA_FULL_INTERLETTER            5
#define EIO                             5
#define MB_LEN_MAX                      5
#define IDC_BUT_SELECT                  5
#define CTFMODEBIAS_NUMERIC             0x0006
#define WB_LEFTBREAK                    6
#define WB_PREVBREAK                    6
#define CFU_UNDERLINEDASHDOT            6
#define PFN_UCROMAN                     6
#define PFA_FULL_SCALED                 6
#define ENXIO                           6
#define CTFMODEBIAS_HIRAGANA            0x0007
#define WB_RIGHTBREAK                   7
#define WB_NEXTBREAK                    7
#define CFU_UNDERLINEDASHDOTDOT         7
#define PFA_FULL_GLYPHS                 7
#define E2BIG                           7
#define SES_MAPCPS                      8
#define IMF_IMEALWAYSSENDNOTIFY         0x0008
#define TO_ADVANCEDLAYOUT               8
#define CTFMODEBIAS_KATAKANA            0x0008
#define ENM_SCROLLEVENTS                0x00000008
#define ES_NOOLEDRAGDROP                0x00000008
#define IMF_CLOSESTATUSWINDOW           0x0008
#define CFM_STRIKEOUT                   0x00000008
#define CFE_STRIKEOUT                   0x0008
#define CFU_UNDERLINEWAVE               8
#define SCF_USEUIRULES                  0x0008
#define PFM_ALIGNMENT                   0x00000008
#define PFA_SNAP_GRID                   8
#define SEL_MULTIOBJECT                 0x0008
#define GT_NOHIDDENTEXT                 8
#define GTL_NUMCHARS                    8
#define BOM_CONTEXTREADING              0x0008
#define BOE_CONTEXTREADING              0x0008
#define _CRT_PACKING                    8
#define _IOMYBUF                        0x0008
#define XML_SKIP_IDS                    8
#define ENOEXEC                         8
#define CHAR_BIT                        8
#define INTR_FLAG                       0x08
#define MAX_DATA_LEN_CAN                8
#define MAX_DATA_LEN_LIN                8
#define LENGTH_STR_TYPE_CAN             8
#define LENGTH_STR_TYPE_LIN             8
#define defBITS_IN_BYTE                 8
#define defDLCSIZE                      8
#define CTFMODEBIAS_HANGUL              0x0009
#define VM_PAGE                         9
#define CFU_UNDERLINETHICK              9
#define EBADF                           9
#define CTFMODEBIAS_HALFWIDTHKATAKANA   0x000A
#define CFU_UNDERLINEHAIRLINE           10
#define ECHILD                          10
#define defBASE_DEC                     10
#define CTFMODEBIAS_FULLWIDTHALPHANUMERIC 0x000B
#define CFU_UNDERLINEDOUBLEWAVE         11
#define EAGAIN                          11
#define CTFMODEBIAS_HALFWIDTHALPHANUMERIC 0x000C
#define CFU_UNDERLINEHEAVYWAVE          12
#define ENOMEM                          12
#define MAX_MSG_WND_COL_CNT             12
#define CFU_UNDERLINELONGDASH           13
#define EACCES                          13
#define CFU_UNDERLINETHICKDASH          14
#define EFAULT                          14
#define CFU_UNDERLINETHICKDASHDOT       15
#define SES_EMULATE10                   16
#define IMF_AUTOFONTSIZEADJUST          0x0010
#define ENM_DRAGDROPDONE                0x00000010
#define WBF_WORDWRAP                    0x010
#define CFM_PROTECTED                   0x00000010
#define CFE_PROTECTED                   0x0010
#define CFU_UNDERLINETHICKDASHDOTDOT    16
#define SCF_ASSOCIATEFONT               0x0010
#define SF_UNICODE                      0x0010
#define PFM_TABSTOPS                    0x00000010
#define GTL_NUMBYTES                    16
#define BOM_CONTEXTALIGNMENT            0x0010
#define BOE_CONTEXTALIGNMENT            0x0010
#define _IOEOF                          0x0010
#define EBUSY                           16
#define LENGTH_STR_TIMESTAMP_CAN        16
#define LENGTH_STR_ID_CAN               16
#define LENGTH_STR_TIMESTAMP_LIN        16
#define LENGTH_STR_ID_LIN               16
#define defBASE_HEX                     16
#define defClockVal                     16
#define CFU_UNDERLINETHICKDOTTED        17
#define EEXIST                          17
#define CFU_UNDERLINETHICKLONGDASH      18
#define EXDEV                           18
#define ENODEV                          19
#define _IOB_ENTRIES                    20
#define FOPEN_MAX                       20
#define _SYS_OPEN                       20
#define ENOTDIR                         20
#define EISDIR                          21
#define ENFILE                          23
#define EMFILE                          24
#define LENGTH_STR_CHKSUM_LIN           24
#define ENOTTY                          25
#define EFBIG                           27
#define ENOSPC                          28
#define ESPIPE                          29
#define EROFS                           30
#define EMLINK                          31
#define defSIM_NETWORK_HANDLE           31
#define SES_USECRLF                     32
#define SES_NOXLTSYMBOLRANGE            32
#define IMF_UIFONTS                     0x0020
#define ENM_PARAGRAPHEXPANDED           0x00000020
#define WBF_WORDBREAK                   0x020
#define IMF_VERTICAL                    0x0020
#define CFM_LINK                        0x00000020
#define CFE_LINK                        0x0020
#define SCF_NOKBUPDATE                  0x0020
#define SF_USECODEPAGE                  0x0020
#define MAX_TAB_STOPS                   32
#define PFM_NUMBERING                   0x00000020
#define _IOERR                          0x0020
#define EPIPE                           32
#define LENGTH_STR_MSGTYPE_LIN          32
#define MAX_DILNAME                     32
#define defPEAK_USB_SIM_NET_HANDLE      32
#define EDOM                            33
#define EDEADLK                         36
#define ENAMETOOLONG                    38
#define ENOLCK                          39
#define ENOSYS                          40
#define ENOTEMPTY                       41
#define MAX_TABLE_CELLS                 63
#define SES_USEAIMM                     64
#define ENM_PAGECHANGE                  0x00000040
#define ECO_AUTOVSCROLL                 0x00000040
#define WBF_OVERFLOW                    0x040
#define IMF_FORCEACTIVE                 0x0040
#define CFM_SMALLCAPS                   0x0040
#define SCF_ASSOCIATEFONT2              0x0040
#define SF_NCRFORNONASCII               0x40
#define PFM_SPACEBEFORE                 0x00000040
#define BOM_LEGACYBIDICLASS             0x0040
#define BOE_LEGACYBIDICLASS             0x0040
#define _IOLBF                          0x0040
#define _IOSTRG                         0x0040
#define MAX_DATA_LEN_CAN_FD             64
//#define EILSEQ                          84
#define defWARNING_LIMIT_INT            96
#define AFX_IDC_LISTBOX                 100
#define _ARGMAX                         100
#define EADDRINUSE                      100
#define AFX_IDC_CHANGE                  101
#define EADDRNOTAVAIL                   101
#define IDD_DIALOG1                     101
#define EAFNOSUPPORT                    102
#define EALREADY                        103
#define EBADMSG                         104
#define ECANCELED                       105
#define IDD_OLE_PROPPAGE_LARGE          105
#define IDD_TAB2                        105
#define IDD_TAB_ACCEPTANCE              105
#define ECONNABORTED                    106
#define ECONNREFUSED                    107
#define ECONNRESET                      108
#define EDESTADDRREQ                    109
#define EHOSTUNREACH                    110
#define EIDRM                           111
#define EINPROGRESS                     112
#define EISCONN                         113
#define ELOOP                           114
#define EMSGSIZE                        115
#define ENETDOWN                        116
#define ENETRESET                       117
#define ENETUNREACH                     118
#define ENOBUFS                         119
#define ENODATA                         120
#define ENOLINK                         121
#define ENOMSG                          122
#define ENOPROTOOPT                     123
#define ENOSR                           124
#define ENOSTR                          125
#define ENOTCONN                        126
#define ENOTRECOVERABLE                 127
#define SCHAR_MAX                       127
#define SES_NOIME                       128
#define IMF_DUALFONT                    0x0080
#define ECO_AUTOHSCROLL                 0x00000080
#define WBF_LEVEL1                      0x080
#define IMF_FORCEINACTIVE               0x0080
#define CFM_ALLCAPS                     0x0080
#define SFF_WRITEXTRAPAR                0x80
#define PFM_SPACEAFTER                  0x00000080
#define _IORW                           0x0080
#define ENOTSOCK                        128
#define MAX_CHAR_SHORT                  128
#define defUSB_PARAM_READ_BUFFER_SIZE   128
#define ENOTSUP                         129
#define EOPNOTSUPP                      130
#define IDD_DLG_HW_LISTING              130
#define EOTHER                          131
#define IDD_OLE_PROPPAGE_LARGE1         131
#define EOVERFLOW                       132
#define IDD_DIALOG_FLEXI_SETTINGS1      132
#define IDD_DIALOG_FLEXI_SETTINGS_TAB   132
#define EOWNERDEAD                      133
#define IDD_TAB_MESSAGE_VIEW            133
#define EPROTO                          134
#define EPROTONOSUPPORT                 135
#define EPROTOTYPE                      136
#define ETIME                           137
#define ETIMEDOUT                       138
#define ETXTBSY                         139
#define EWOULDBLOCK                     140
#define AFX_IDC_PRINT_DOCNAME           201
#define AFX_IDC_PRINT_PRINTERNAME       202
#define AFX_IDC_PRINT_PORTNAME          203
#define AFX_IDC_PRINT_PAGENUM           204
#define IDR_BMP_NET                     204
#define CFU_INVERT                      0xFE
#define _SECURECRT_FILL_BUFFER_PATTERN  0xFE
#define MAX_DATA_LEN_FLEXRAY            254
#define CFU_CF1UNDERLINE                0xFF
#define UCHAR_MAX                       0xff
#define SUBVERSION_MASK                 0x000000FF
#define defINIT_MASK_VALUE              0xFF
#define SES_ALLOWBEEPS                  256
#define ECO_NOHIDESEL                   0x00000100
#define WBF_LEVEL2                      0x100
#define IMF_FORCEREMEMBER               0x0100
#define CFM_HIDDEN                      0x0100
#define PFM_LINESPACING                 0x00000100
#define PFNS_PARENS                     0x100
#define _MAX_DIR                        256
#define _MAX_FNAME                      256
#define _MAX_EXT                        256
#define LENGTH_STR_DATA_CAN             256
#define LENGTH_STR_DESCRIPTION_CAN      256
#define LENGTH_STR_DATA_LIN             256
#define LENGTH_STR_DESCRIPTION_LIN      256
#define FILENAME_MAX                    260
#define _MAX_PATH                       260
#define WM_UNICHAR                      0x0109
#define _LIBICONV_VERSION               0x0109
#define defBAUD_RATE_VAL                500
#define SES_UPPERCASE                   512
#define WBF_CUSTOM                      0x200
#define CFM_OUTLINE                     0x0200
#define PFNS_PERIOD                     0x200
#define BUFSIZ                          512
#define _NSTREAM_                       512
#define _WIN32_IE_IE20                  0x0200
#define MAX_CHAR_LONG                   512
#define lDefaultTab                     720
//#define _RICHEDIT_VER                   0x0300
#define PFNS_PLAIN                      0x300
#define _WIN32_IE_IE30                  0x0300
#define _WIN32_IE_IE302                 0x0302
#define AFX_IDC_FONTPROP                1000
#define AFX_IDC_FONTNAMES               1001
#define AFX_IDC_FONTSTYLES              1002
#define AFX_IDC_FONTSIZES               1003
#define AFX_IDC_STRIKEOUT               1004
#define IDC_TABCONTROL                  1004
#define AFX_IDC_UNDERLINE               1005
#define AFX_IDC_SAMPLEBOX               1006
#define IDC_EDIT_NET_NAME               1007
#define IDC_EDIT_FIRMWARE               1008
#define IDC_EDIT_NET_NAME2              1009
#define IDC_EDIT_NET_ADDITIONALINFO     1009
#define IDC_LSTC_HW_LIST                1018
#define IDC_EDIT_DRIVER_ID              1019
#define IDC_BUT_BLINK                   1020
#define SES_LOWERCASE                   1024
#define IMF_NORTFFONTSUBSTITUTE         0x0400
#define IMF_MULTIPLEEDIT                0x0400
#define CFM_SHADOW                      0x0400
#define PFM_STYLE                       0x00000400
#define PFNS_NONUMBER                   0x400
#define _WIN32_WINNT_NT4                0x0400
#define _WIN32_IE_IE40                  0x0400
#define MAX_CHAR                        1024
#define defUSB_PARAM_BUFFER_SIZE        1024
#define _WIN32_IE_IE401                 0x0401
#define AFX_IDC_COLOR_BLACK             1100
#define AFX_IDC_COLOR_WHITE             1101
#define AFX_IDC_COLOR_RED               1102
#define AFX_IDC_COLOR_GREEN             1103
#define AFX_IDC_COLOR_BLUE              1104
#define AFX_IDC_COLOR_YELLOW            1105
#define AFX_IDC_COLOR_MAGENTA           1106
#define AFX_IDC_COLOR_CYAN              1107
#define AFX_IDC_COLOR_GRAY              1108
#define AFX_IDC_COLOR_LIGHTGRAY         1109
#define AFX_IDC_COLOR_DARKRED           1110
#define AFX_IDC_COLOR_DARKGREEN         1111
#define AFX_IDC_COLOR_DARKBLUE          1112
#define AFX_IDC_COLOR_LIGHTBROWN        1113
#define AFX_IDC_COLOR_DARKMAGENTA       1114
#define AFX_IDC_COLOR_DARKCYAN          1115
#define AFX_IDC_COLORPROP               1116
#define AFX_IDC_SYSTEMCOLORS            1117
#define IDC_STAT_LINE3                  1119
#define AFX_IDC_PROPNAME                1201
#define AFX_IDC_PICTURE                 1202
#define AFX_IDC_BROWSE                  1203
#define AFX_IDC_CLEAR                   1204
#define IDC_EDIT_ACC_CODE               1217
#define IDC_EDIT_ACC_MASK               1219
#define IDC_LSTC_SELECTED_HW_LIST       1226
#define _WIN32_WINNT_WIN2K              0x0500
#define _WIN32_IE_IE50                  0x0500
#define _WIN32_WINNT_WINXP              0x0501
#define _WIN32_IE_IE501                 0x0501
#define _WIN32_WINNT_WS03               0x0502
#define _WIN32_IE_IE55                  0x0550
#define _WIN32_WINNT_WIN6               0x0600
#define _WIN32_WINNT_VISTA              0x0600
#define _WIN32_WINNT_WS08               0x0600
#define _WIN32_WINNT_LONGHORN           0x0600
#define _WIN32_IE_IE60                  0x0600
#define _WIN32_WINNT_WIN7               0x0601
#define _WIN32_IE_IE60SP1               0x0601
#define _WIN32_IE_WS03                  0x0602
#define _WIN32_IE_IE60SP2               0x0603
#define yHeightCharPtsMost              1638
#define MAX_DATA_LEN_J1939              1785
#define EN_MSGFILTER                    0x0700
#define SF_RTFVAL                       0x0700
#define _WIN32_IE_IE70                  0x0700
#define EN_REQUESTRESIZE                0x0701
#define EN_SELCHANGE                    0x0702
#define EN_DROPFILES                    0x0703
#define EN_PROTECTED                    0x0704
#define EN_CORRECTTEXT                  0x0705
#define EN_STOPNOUNDO                   0x0706
#define EN_IMECHANGE                    0x0707
#define EN_SAVECLIPBOARD                0x0708
#define EN_OLEOPFAILED                  0x0709
#define EN_OBJECTPOSITIONS              0x070a
#define EN_LINK                         0x070b
#define EN_DRAGDROPDONE                 0x070c
#define EN_PARAGRAPHEXPANDED            0x070d
#define EN_PAGECHANGE                   0x070e
#define EN_LOWFIRTF                     0x070f
#define EN_ALIGNLTR                     0x0710
#define EN_ALIGNRTL                     0x0711
#define SES_NOINPUTSEQUENCECHK          2048
#define ECO_READONLY                    0x00000800
#define CFM_EMBOSS                      0x0800
#define SFF_PWD                         0x0800
#define PFM_BORDER                      0x00000800
#define _WIN32_IE_IE80                  0x0800
#define IDR_PGM_EDTYPE                  3008
#define SES_BIDI                        4096
#define ECO_WANTRETURN                  0x00001000
#define CFM_IMPRINT                     0x1000
#define SFF_KEEPDOCINFO                 0x1000
#define PFM_SHADING                     0x00001000
#define BASE_BUFFER_SIZE                4096
#define SES_SCROLLONKILLFOCUS           8192
#define ES_DISABLENOSCROLL              0x00002000
#define CFM_DISABLED                    0x2000
#define SFF_PERSISTVIEWSCALE            0x2000
#define PFM_NUMBERINGSTYLE              0x00002000
#define AFX_IDC_TAB_CONTROL             0x3020
#define ID_APPLY_NOW                    0x3021
#define ID_WIZBACK                      0x3023
#define ID_WIZNEXT                      0x3024
#define ID_WIZFINISH                    0x3025
#define SES_XLTCRCRLFTOCR               16384
#define ES_SUNKEN                       0x00004000
#define CFM_REVISED                     0x4000
#define SFF_PLAINRTF                    0x4000
#define PFM_NUMBERINGTAB                0x00004000
#define LIBXML_VERSION                  20708
#define AFX_IDD_NEWTYPEDLG              30721
#define AFX_IDD_PRINTDLG                30722
#define AFX_IDD_PREVIEW_TOOLBAR         30723
#define AFX_IDD_INSERTOBJECT            30724
#define AFX_IDD_CHANGEICON              30725
#define AFX_IDD_CONVERT                 30726
#define AFX_IDD_PASTESPECIAL            30727
#define AFX_IDD_EDITLINKS               30728
#define AFX_IDD_FILEBROWSE              30729
#define AFX_IDD_BUSY                    30730
#define AFX_IDD_OBJECTPROPERTIES        30732
#define AFX_IDD_CHANGESOURCE            30733
#define AFX_IDC_CONTEXTHELP             30977
#define AFX_IDC_MAGNIFY                 30978
#define AFX_IDC_SMALLARROWS             30979
#define AFX_IDC_HSPLITBAR               30980
#define AFX_IDC_VSPLITBAR               30981
#define AFX_IDC_NODROPCRSR              30982
#define AFX_IDC_TRACKNWSE               30983
#define AFX_IDC_TRACKNESW               30984
#define AFX_IDC_TRACKNS                 30985
#define AFX_IDC_TRACKWE                 30986
#define AFX_IDC_TRACK4WAY               30987
#define AFX_IDC_MOVE4WAY                30988
#define AFX_IDB_MINIFRAME_MENU          30994
#define AFX_IDB_CHECKLISTBOX_NT         30995
#define AFX_IDB_CHECKLISTBOX_95         30996
#define AFX_IDR_PREVIEW_ACCEL           30997
#define AFX_IDI_STD_MDIFRAME            31233
#define AFX_IDI_STD_FRAME               31234
#define AFX_IDD_PROPPAGE_COLOR          32257
#define AFX_IDD_PROPPAGE_FONT           32258
#define AFX_IDD_PROPPAGE_PICTURE        32259
#define AFX_IDB_TRUETYPE                32384
#define cchTextLimitDefault             32767
#define TMP_MAX                         32767
#define SHRT_MAX                        32767
#define RAND_MAX                        0x7fff
#define _MAX_ENV                        32767
#define MAX_DATA_LEN_MCNET              0x7FFF
#define SES_DRAFTMODE                   32768
#define ES_SAVESEL                      0x00008000
#define ECO_SAVESEL                     0x00008000
#define CFM_REVAUTHOR                   0x00008000
#define SFF_SELECTION                   0x8000
#define PFM_NUMBERINGSTART              0x00008000
#define PFNS_NEWNUMBER                  0x8000
#define GCM_RIGHTMOUSEDROP              0x8000
//#define SHRT_MIN                        -32768
#define IDC_FLEXI_GROUP_KEY             40000
#define IDC_FLEXI_GROUP_SEND            40000
#define IDC_FLEXI_CC0_PREF              40001
#define IDD_STATIC_TEXT_LOWER           40001
#define IDD_TAB_TRANSMISSION            40001
#define IDC_FLEXI_CC1_PREF              40002
#define IDC_FLEXI_CONTINUOUS_DYN        40002
#define IDC_FLEXI_CC0_START_SYNC        40003
#define IDC_FLEXI_SINGLE_DYN            40003
#define IDC_FLEXI_CC1_START_SYNC        40004
#define IDC_FLEXI_GROUP_TRANS           40004
#define IDC_FLEXI_ACCEPT_1              40005
#define IDC_FLEXI_CC0_MANUAL            40005
#define IDC_FLEXI_CC1_MANUAL            40006
#define IDC_FLEXI_CONTINUOUS_STATIC     40006
#define IDC_FLEXI_GROUP_SEND_STATIC     40007
#define IDC_STATIC_TEXT_CC0_MAN         40007
#define IDC_FLEXI_GROUP_SEND_DYN        40008
#define IDC_STATIC_TEXT_CC0             40008
#define IDC_FLEXI_SINGLE_STATIC         40009
#define IDC_STATIC_TEXT_CC1_MAN         40009
#define IDC_FLEXI_NULL                  40010
#define IDC_STATIC_TEXT_CC1             40010
#define IDC_FLEXI_STARTUP               40011
#define IDC_FLEXI_GROUP_FIFO            40012
#define IDC_FLEXI_CHECK_FIFO_1          40013
#define IDC_FLEXI_CHECK_FIFO_2          40014
#define IDC_FLEXI_CHECK_FIFO_3          40015
#define IDC_FLEXI_ACCEPT_0              40016
#define IDC_FLEXI_CHECK_FIFO_0          40017
#define IDC_FLEXI_LOW_LIMIT_0           40018
#define IDC_FLEXI_LOW_LIMIT_1           40019
#define IDC_FLEXI_LOW_LIMIT_2           40020
#define IDC_FLEXI_UPPER_LIMIT_1         40021
#define IDC_FLEXI_UPPER_LIMIT_2         40022
#define IDC_FLEXI_UPPER_LIMIT_3         40023
#define IDC_FLEXI_LOW_LIMIT_3           40024
#define IDC_FLEXI_ACCEPT_2              40025
#define IDC_FLEXI_ACCEPT_3              40026
#define IDC_FLEXI_REJECT_0              40027
#define IDC_FLEXI_REJECT_1              40028
#define IDC_FLEXI_REJECT_2              40029
#define IDC_FLEXI_REJECT_3              40030
#define IDC_FLEXI_UPDATE                40031
#define IDD_STATIC_TEXT_UPPER           40032
#define IDC_FLEXI_UPPER_LIMIT_0         40033
#define IDD_DIALOG_FLEXI_SETTINGS       41100
#define IDD_DIALOG_FLEXI_KEYSLOT        41568
#define defBAUD_RATE                    0xC03A
#define NO_SELECTION_HI                 0xCDCD
#define AFX_IDS_APP_TITLE               0xE000
#define AFX_IDS_IDLEMESSAGE             0xE001
#define AFX_IDS_HELPMODEMESSAGE         0xE002
#define AFX_IDS_APP_TITLE_EMBEDDING     0xE003
#define AFX_IDS_COMPANY_NAME            0xE004
#define AFX_IDS_OBJ_TITLE_INPLACE       0xE005
#define ID_FILE_NEW                     0xE100
#define ID_FILE_OPEN                    0xE101
#define ID_FILE_CLOSE                   0xE102
#define ID_FILE_SAVE                    0xE103
#define ID_FILE_SAVE_AS                 0xE104
#define ID_FILE_PAGE_SETUP              0xE105
#define ID_FILE_PRINT_SETUP             0xE106
#define ID_FILE_PRINT                   0xE107
#define ID_FILE_PRINT_DIRECT            0xE108
#define ID_FILE_PRINT_PREVIEW           0xE109
#define ID_FILE_UPDATE                  0xE10A
#define ID_FILE_SAVE_COPY_AS            0xE10B
#define ID_FILE_SEND_MAIL               0xE10C
#define ID_FILE_MRU_FIRST               0xE110
#define ID_FILE_MRU_FILE1               0xE110
#define ID_FILE_MRU_FILE2               0xE111
#define ID_FILE_MRU_FILE3               0xE112
#define ID_FILE_MRU_FILE4               0xE113
#define ID_FILE_MRU_FILE5               0xE114
#define ID_FILE_MRU_FILE6               0xE115
#define ID_FILE_MRU_FILE7               0xE116
#define ID_FILE_MRU_FILE8               0xE117
#define ID_FILE_MRU_FILE9               0xE118
#define ID_FILE_MRU_FILE10              0xE119
#define ID_FILE_MRU_FILE11              0xE11A
#define ID_FILE_MRU_FILE12              0xE11B
#define ID_FILE_MRU_FILE13              0xE11C
#define ID_FILE_MRU_FILE14              0xE11D
#define ID_FILE_MRU_FILE15              0xE11E
#define ID_FILE_MRU_FILE16              0xE11F
#define ID_FILE_MRU_LAST                0xE11F
#define ID_EDIT_CLEAR                   0xE120
#define ID_EDIT_CLEAR_ALL               0xE121
#define ID_EDIT_COPY                    0xE122
#define ID_EDIT_CUT                     0xE123
#define ID_EDIT_FIND                    0xE124
#define ID_EDIT_PASTE                   0xE125
#define ID_EDIT_PASTE_LINK              0xE126
#define ID_EDIT_PASTE_SPECIAL           0xE127
#define ID_EDIT_REPEAT                  0xE128
#define ID_EDIT_REPLACE                 0xE129
#define ID_EDIT_SELECT_ALL              0xE12A
#define ID_EDIT_UNDO                    0xE12B
#define ID_EDIT_REDO                    0xE12C
#define ID_WINDOW_NEW                   0xE130
#define ID_WINDOW_ARRANGE               0xE131
#define ID_WINDOW_CASCADE               0xE132
#define ID_WINDOW_TILE_HORZ             0xE133
#define ID_WINDOW_TILE_VERT             0xE134
#define ID_WINDOW_SPLIT                 0xE135
#define ID_APP_ABOUT                    0xE140
#define ID_APP_EXIT                     0xE141
#define ID_HELP_INDEX                   0xE142
#define ID_HELP_FINDER                  0xE143
#define ID_HELP_USING                   0xE144
#define ID_CONTEXT_HELP                 0xE145
#define ID_HELP                         0xE146
#define ID_DEFAULT_HELP                 0xE147
#define ID_NEXT_PANE                    0xE150
#define ID_PREV_PANE                    0xE151
#define ID_FORMAT_FONT                  0xE160
#define ID_OLE_INSERT_NEW               0xE200
#define ID_OLE_EDIT_LINKS               0xE201
#define ID_OLE_EDIT_CONVERT             0xE202
#define ID_OLE_EDIT_CHANGE_ICON         0xE203
#define ID_OLE_EDIT_PROPERTIES          0xE204
#define ID_OLE_VERB_FIRST               0xE210
#define AFX_ID_PREVIEW_CLOSE            0xE300
#define AFX_ID_PREVIEW_NUMPAGE          0xE301
#define AFX_ID_PREVIEW_NEXT             0xE302
#define AFX_ID_PREVIEW_PREV             0xE303
#define AFX_ID_PREVIEW_PRINT            0xE304
#define AFX_ID_PREVIEW_ZOOMIN           0xE305
#define AFX_ID_PREVIEW_ZOOMOUT          0xE306
#define ID_INDICATOR_EXT                0xE700
#define ID_INDICATOR_CAPS               0xE701
#define ID_INDICATOR_NUM                0xE702
#define ID_INDICATOR_SCRL               0xE703
#define ID_INDICATOR_OVR                0xE704
#define ID_INDICATOR_REC                0xE705
#define ID_INDICATOR_KANA               0xE706
#define ID_VIEW_TOOLBAR                 0xE800
#define ID_VIEW_STATUS_BAR              0xE801
#define ID_VIEW_REBAR                   0xE804
#define ID_VIEW_AUTOARRANGE             0xE805
#define ID_VIEW_SMALLICON               0xE810
#define ID_VIEW_LARGEICON               0xE811
#define ID_VIEW_LIST                    0xE812
#define ID_VIEW_DETAILS                 0xE813
#define ID_VIEW_LINEUP                  0xE814
#define ID_VIEW_BYNAME                  0xE815
#define ID_RECORD_FIRST                 0xE900
#define ID_RECORD_LAST                  0xE901
#define ID_RECORD_NEXT                  0xE902
#define ID_RECORD_PREV                  0xE903
#define defMAX_TIME_DELAY               60000
#define AFX_IDS_SCSIZE                  0xEF00
#define AFX_IDS_SCMOVE                  0xEF01
#define AFX_IDS_SCMINIMIZE              0xEF02
#define AFX_IDS_SCMAXIMIZE              0xEF03
#define AFX_IDS_SCNEXTWINDOW            0xEF04
#define AFX_IDS_SCPREVWINDOW            0xEF05
#define AFX_IDS_SCCLOSE                 0xEF06
#define AFX_IDS_SCRESTORE               0xEF12
#define AFX_IDS_SCTASKLIST              0xEF13
#define AFX_IDS_MDICHILD                0xEF1F
#define AFX_IDS_DESKACCESSORY           0xEFDA
#define AFX_IDS_OPENFILE                0xF000
#define AFX_IDS_SAVEFILE                0xF001
#define AFX_IDS_ALLFILTER               0xF002
#define AFX_IDS_UNTITLED                0xF003
#define AFX_IDS_SAVEFILECOPY            0xF004
#define AFX_IDS_PREVIEW_CLOSE           0xF005
#define AFX_IDS_UNNAMED_FILE            0xF006
#define AFX_IDS_HIDE                    0xF011
#define AFX_IDP_NO_ERROR_AVAILABLE      0xF020
#define AFX_IDS_NOT_SUPPORTED_EXCEPTION 0xF021
#define AFX_IDS_RESOURCE_EXCEPTION      0xF022
#define AFX_IDS_MEMORY_EXCEPTION        0xF023
#define AFX_IDS_USER_EXCEPTION          0xF024
#define AFX_IDS_INVALID_ARG_EXCEPTION   0xF025
#define AFX_IDS_PRINTONPORT             0xF040
#define AFX_IDS_ONEPAGE                 0xF041
#define AFX_IDS_TWOPAGE                 0xF042
#define AFX_IDS_PRINTPAGENUM            0xF043
#define AFX_IDS_PREVIEWPAGEDESC         0xF044
#define AFX_IDS_PRINTDEFAULTEXT         0xF045
#define AFX_IDS_PRINTDEFAULT            0xF046
#define AFX_IDS_PRINTFILTER             0xF047
#define AFX_IDS_PRINTCAPTION            0xF048
#define AFX_IDS_PRINTTOFILE             0xF049
#define AFX_IDS_OBJECT_MENUITEM         0xF080
#define AFX_IDS_EDIT_VERB               0xF081
#define AFX_IDS_ACTIVATE_VERB           0xF082
#define AFX_IDS_CHANGE_LINK             0xF083
#define AFX_IDS_AUTO                    0xF084
#define AFX_IDS_MANUAL                  0xF085
#define AFX_IDS_FROZEN                  0xF086
#define AFX_IDS_ALL_FILES               0xF087
#define AFX_IDS_SAVE_MENU               0xF088
#define AFX_IDS_UPDATE_MENU             0xF089
#define AFX_IDS_SAVE_AS_MENU            0xF08A
#define AFX_IDS_SAVE_COPY_AS_MENU       0xF08B
#define AFX_IDS_EXIT_MENU               0xF08C
#define AFX_IDS_UPDATING_ITEMS          0xF08D
#define AFX_IDS_METAFILE_FORMAT         0xF08E
#define AFX_IDS_DIB_FORMAT              0xF08F
#define AFX_IDS_BITMAP_FORMAT           0xF090
#define AFX_IDS_LINKSOURCE_FORMAT       0xF091
#define AFX_IDS_EMBED_FORMAT            0xF092
#define AFX_IDS_PASTELINKEDTYPE         0xF094
#define AFX_IDS_UNKNOWNTYPE             0xF095
#define AFX_IDS_RTF_FORMAT              0xF096
#define AFX_IDS_TEXT_FORMAT             0xF097
#define AFX_IDS_INVALID_CURRENCY        0xF098
#define AFX_IDS_INVALID_DATETIME        0xF099
#define AFX_IDS_INVALID_DATETIMESPAN    0xF09A
#define AFX_IDP_INVALID_FILENAME        0xF100
#define AFX_IDP_FAILED_TO_OPEN_DOC      0xF101
#define AFX_IDP_FAILED_TO_SAVE_DOC      0xF102
#define AFX_IDP_ASK_TO_SAVE             0xF103
#define AFX_IDP_FAILED_TO_CREATE_DOC    0xF104
#define AFX_IDP_FILE_TOO_LARGE          0xF105
#define AFX_IDP_FAILED_TO_START_PRINT   0xF106
#define AFX_IDP_FAILED_TO_LAUNCH_HELP   0xF107
#define AFX_IDP_INTERNAL_FAILURE        0xF108
#define AFX_IDP_COMMAND_FAILURE         0xF109
#define AFX_IDP_FAILED_MEMORY_ALLOC     0xF10A
#define AFX_IDP_UNREG_DONE              0xF10B
#define AFX_IDP_UNREG_FAILURE           0xF10C
#define AFX_IDP_DLL_LOAD_FAILED         0xF10D
#define AFX_IDP_DLL_BAD_VERSION         0xF10E
#define AFX_IDP_PARSE_INT               0xF110
#define AFX_IDP_PARSE_REAL              0xF111
#define AFX_IDP_PARSE_INT_RANGE         0xF112
#define AFX_IDP_PARSE_REAL_RANGE        0xF113
#define AFX_IDP_PARSE_STRING_SIZE       0xF114
#define AFX_IDP_PARSE_RADIO_BUTTON      0xF115
#define AFX_IDP_PARSE_BYTE              0xF116
#define AFX_IDP_PARSE_UINT              0xF117
#define AFX_IDP_PARSE_DATETIME          0xF118
#define AFX_IDP_PARSE_CURRENCY          0xF119
#define AFX_IDP_FAILED_INVALID_FORMAT   0xF120
#define AFX_IDP_FAILED_INVALID_PATH     0xF121
#define AFX_IDP_FAILED_DISK_FULL        0xF122
#define AFX_IDP_FAILED_ACCESS_READ      0xF123
#define AFX_IDP_FAILED_ACCESS_WRITE     0xF124
#define AFX_IDP_FAILED_IO_ERROR_READ    0xF125
#define AFX_IDP_FAILED_IO_ERROR_WRITE   0xF126
#define AFX_IDP_STATIC_OBJECT           0xF180
#define AFX_IDP_FAILED_TO_CONNECT       0xF181
#define AFX_IDP_SERVER_BUSY             0xF182
#define AFX_IDP_BAD_VERB                0xF183
#define AFX_IDS_NOT_DOCOBJECT           0xF184
#define AFX_IDP_FAILED_TO_NOTIFY        0xF185
#define AFX_IDP_FAILED_TO_LAUNCH        0xF186
#define AFX_IDP_ASK_TO_UPDATE           0xF187
#define AFX_IDP_FAILED_TO_UPDATE        0xF188
#define AFX_IDP_FAILED_TO_REGISTER      0xF189
#define AFX_IDP_FAILED_TO_AUTO_REGISTER 0xF18A
#define AFX_IDP_FAILED_TO_CONVERT       0xF18B
#define AFX_IDP_GET_NOT_SUPPORTED       0xF18C
#define AFX_IDP_SET_NOT_SUPPORTED       0xF18D
#define AFX_IDP_ASK_TO_DISCARD          0xF18E
#define AFX_IDP_FAILED_TO_CREATE        0xF18F
#define AFX_IDP_FAILED_MAPI_LOAD        0xF190
#define AFX_IDP_INVALID_MAPI_DLL        0xF191
#define AFX_IDP_FAILED_MAPI_SEND        0xF192
#define AFX_IDP_FILE_NONE               0xF1A0
#define AFX_IDP_FILE_GENERIC            0xF1A1
#define AFX_IDP_FILE_NOT_FOUND          0xF1A2
#define AFX_IDP_FILE_BAD_PATH           0xF1A3
#define AFX_IDP_FILE_TOO_MANY_OPEN      0xF1A4
#define AFX_IDP_FILE_ACCESS_DENIED      0xF1A5
#define AFX_IDP_FILE_INVALID_FILE       0xF1A6
#define AFX_IDP_FILE_REMOVE_CURRENT     0xF1A7
#define AFX_IDP_FILE_DIR_FULL           0xF1A8
#define AFX_IDP_FILE_BAD_SEEK           0xF1A9
#define AFX_IDP_FILE_HARD_IO            0xF1AA
#define AFX_IDP_FILE_SHARING            0xF1AB
#define AFX_IDP_FILE_LOCKING            0xF1AC
#define AFX_IDP_FILE_DISKFULL           0xF1AD
#define AFX_IDP_FILE_EOF                0xF1AE
#define AFX_IDP_ARCH_NONE               0xF1B0
#define AFX_IDP_ARCH_GENERIC            0xF1B1
#define AFX_IDP_ARCH_READONLY           0xF1B2
#define AFX_IDP_ARCH_ENDOFFILE          0xF1B3
#define AFX_IDP_ARCH_WRITEONLY          0xF1B4
#define AFX_IDP_ARCH_BADINDEX           0xF1B5
#define AFX_IDP_ARCH_BADCLASS           0xF1B6
#define AFX_IDP_ARCH_BADSCHEMA          0xF1B7
#define AFX_IDS_OCC_SCALEUNITS_PIXELS   0xF1C0
#define AFX_IDS_STATUS_FONT             0xF230
#define AFX_IDS_TOOLTIP_FONT            0xF231
#define AFX_IDS_UNICODE_FONT            0xF232
#define AFX_IDS_MINI_FONT               0xF233
#define AFX_IDP_SQL_CONNECT_FAIL        0xF281
#define AFX_IDP_SQL_RECORDSET_FORWARD_ONLY 0xF282
#define AFX_IDP_SQL_EMPTY_COLUMN_LIST   0xF283
#define AFX_IDP_SQL_FIELD_SCHEMA_MISMATCH 0xF284
#define AFX_IDP_SQL_ILLEGAL_MODE        0xF285
#define AFX_IDP_SQL_MULTIPLE_ROWS_AFFECTED 0xF286
#define AFX_IDP_SQL_NO_CURRENT_RECORD   0xF287
#define AFX_IDP_SQL_NO_ROWS_AFFECTED    0xF288
#define AFX_IDP_SQL_RECORDSET_READONLY  0xF289
#define AFX_IDP_SQL_SQL_NO_TOTAL        0xF28A
#define AFX_IDP_SQL_ODBC_LOAD_FAILED    0xF28B
#define AFX_IDP_SQL_DYNASET_NOT_SUPPORTED 0xF28C
#define AFX_IDP_SQL_SNAPSHOT_NOT_SUPPORTED 0xF28D
#define AFX_IDP_SQL_API_CONFORMANCE     0xF28E
#define AFX_IDP_SQL_SQL_CONFORMANCE     0xF28F
#define AFX_IDP_SQL_NO_DATA_FOUND       0xF290
#define AFX_IDP_SQL_ROW_UPDATE_NOT_SUPPORTED 0xF291
#define AFX_IDP_SQL_ODBC_V2_REQUIRED    0xF292
#define AFX_IDP_SQL_NO_POSITIONED_UPDATES 0xF293
#define AFX_IDP_SQL_LOCK_MODE_NOT_SUPPORTED 0xF294
#define AFX_IDP_SQL_DATA_TRUNCATED      0xF295
#define AFX_IDP_SQL_ROW_FETCH           0xF296
#define AFX_IDP_SQL_INCORRECT_ODBC      0xF297
#define AFX_IDP_SQL_UPDATE_DELETE_FAILED 0xF298
#define AFX_IDP_SQL_DYNAMIC_CURSOR_NOT_SUPPORTED 0xF299
#define AFX_IDP_SQL_FIELD_NOT_FOUND     0xF29A
#define AFX_IDP_SQL_BOOKMARKS_NOT_SUPPORTED 0xF29B
#define AFX_IDP_SQL_BOOKMARKS_NOT_ENABLED 0xF29C
#define AFX_IDS_DELETED                 0xF29D
#define AFX_IDP_DAO_ENGINE_INITIALIZATION 0xF2B0
#define AFX_IDP_DAO_DFX_BIND            0xF2B1
#define AFX_IDP_DAO_OBJECT_NOT_OPEN     0xF2B2
#define AFX_IDP_DAO_ROWTOOSHORT         0xF2B3
#define AFX_IDP_DAO_BADBINDINFO         0xF2B4
#define AFX_IDP_DAO_COLUMNUNAVAILABLE   0xF2B5
#define AFX_IDS_HTTP_TITLE              0xF2D1
#define AFX_IDS_HTTP_NO_TEXT            0xF2D2
#define AFX_IDS_HTTP_BAD_REQUEST        0xF2D3
#define AFX_IDS_HTTP_AUTH_REQUIRED      0xF2D4
#define AFX_IDS_HTTP_FORBIDDEN          0xF2D5
#define AFX_IDS_HTTP_NOT_FOUND          0xF2D6
#define AFX_IDS_HTTP_SERVER_ERROR       0xF2D7
#define AFX_IDS_HTTP_NOT_IMPLEMENTED    0xF2D8
#define AFX_IDS_PROPPAGE_UNKNOWN        0xFE01
#define AFX_IDS_COLOR_DESKTOP           0xFE04
#define AFX_IDS_COLOR_APPWORKSPACE      0xFE05
#define AFX_IDS_COLOR_WNDBACKGND        0xFE06
#define AFX_IDS_COLOR_WNDTEXT           0xFE07
#define AFX_IDS_COLOR_MENUBAR           0xFE08
#define AFX_IDS_COLOR_MENUTEXT          0xFE09
#define AFX_IDS_COLOR_ACTIVEBAR         0xFE0A
#define AFX_IDS_COLOR_INACTIVEBAR       0xFE0B
#define AFX_IDS_COLOR_ACTIVETEXT        0xFE0C
#define AFX_IDS_COLOR_INACTIVETEXT      0xFE0D
#define AFX_IDS_COLOR_ACTIVEBORDER      0xFE0E
#define AFX_IDS_COLOR_INACTIVEBORDER    0xFE0F
#define AFX_IDS_COLOR_WNDFRAME          0xFE10
#define AFX_IDS_COLOR_SCROLLBARS        0xFE11
#define AFX_IDS_COLOR_BTNFACE           0xFE12
#define AFX_IDS_COLOR_BTNSHADOW         0xFE13
#define AFX_IDS_COLOR_BTNTEXT           0xFE14
#define AFX_IDS_COLOR_BTNHIGHLIGHT      0xFE15
#define AFX_IDS_COLOR_DISABLEDTEXT      0xFE16
#define AFX_IDS_COLOR_HIGHLIGHT         0xFE17
#define AFX_IDS_COLOR_HIGHLIGHTTEXT     0xFE18
#define AFX_IDS_REGULAR                 0xFE19
#define AFX_IDS_BOLD                    0xFE1A
#define AFX_IDS_ITALIC                  0xFE1B
#define AFX_IDS_BOLDITALIC              0xFE1C
#define AFX_IDS_SAMPLETEXT              0xFE1D
#define AFX_IDS_DISPLAYSTRING_FONT      0xFE1E
#define AFX_IDS_DISPLAYSTRING_COLOR     0xFE1F
#define AFX_IDS_DISPLAYSTRING_PICTURE   0xFE20
#define AFX_IDS_PICTUREFILTER           0xFE21
#define AFX_IDS_PICTYPE_UNKNOWN         0xFE22
#define AFX_IDS_PICTYPE_NONE            0xFE23
#define AFX_IDS_PICTYPE_BITMAP          0xFE24
#define AFX_IDS_PICTYPE_METAFILE        0xFE25
#define AFX_IDS_PICTYPE_ICON            0xFE26
#define AFX_IDS_COLOR_PPG               0xFE28
#define AFX_IDS_COLOR_PPG_CAPTION       0xFE29
#define AFX_IDS_FONT_PPG                0xFE2A
#define AFX_IDS_FONT_PPG_CAPTION        0xFE2B
#define AFX_IDS_PICTURE_PPG             0xFE2C
#define AFX_IDS_PICTURE_PPG_CAPTION     0xFE2D
#define AFX_IDS_PICTUREBROWSETITLE      0xFE30
#define AFX_IDS_BORDERSTYLE_0           0xFE31
#define AFX_IDS_BORDERSTYLE_1           0xFE32
#define AFX_IDS_VERB_EDIT               0xFE40
#define AFX_IDS_VERB_PROPERTIES         0xFE41
#define AFX_IDP_PICTURECANTOPEN         0xFE83
#define AFX_IDP_PICTURECANTLOAD         0xFE84
#define AFX_IDP_PICTURETOOLARGE         0xFE85
#define AFX_IDP_PICTUREREADFAILED       0xFE86
#define AFX_IDP_E_ILLEGALFUNCTIONCALL   0xFEA0
#define AFX_IDP_E_OVERFLOW              0xFEA1
#define AFX_IDP_E_OUTOFMEMORY           0xFEA2
#define AFX_IDP_E_DIVISIONBYZERO        0xFEA3
#define AFX_IDP_E_OUTOFSTRINGSPACE      0xFEA4
#define AFX_IDP_E_OUTOFSTACKSPACE       0xFEA5
#define AFX_IDP_E_BADFILENAMEORNUMBER   0xFEA6
#define AFX_IDP_E_FILENOTFOUND          0xFEA7
#define AFX_IDP_E_BADFILEMODE           0xFEA8
#define AFX_IDP_E_FILEALREADYOPEN       0xFEA9
#define AFX_IDP_E_DEVICEIOERROR         0xFEAA
#define AFX_IDP_E_FILEALREADYEXISTS     0xFEAB
#define AFX_IDP_E_BADRECORDLENGTH       0xFEAC
#define AFX_IDP_E_DISKFULL              0xFEAD
#define AFX_IDP_E_BADRECORDNUMBER       0xFEAE
#define AFX_IDP_E_BADFILENAME           0xFEAF
#define AFX_IDP_E_TOOMANYFILES          0xFEB0
#define AFX_IDP_E_DEVICEUNAVAILABLE     0xFEB1
#define AFX_IDP_E_PERMISSIONDENIED      0xFEB2
#define AFX_IDP_E_DISKNOTREADY          0xFEB3
#define AFX_IDP_E_PATHFILEACCESSERROR   0xFEB4
#define AFX_IDP_E_PATHNOTFOUND          0xFEB5
#define AFX_IDP_E_INVALIDPATTERNSTRING  0xFEB6
#define AFX_IDP_E_INVALIDUSEOFNULL      0xFEB7
#define AFX_IDP_E_INVALIDFILEFORMAT     0xFEB8
#define AFX_IDP_E_INVALIDPROPERTYVALUE  0xFEB9
#define AFX_IDP_E_INVALIDPROPERTYARRAYINDEX 0xFEBA
#define AFX_IDP_E_SETNOTSUPPORTEDATRUNTIME 0xFEBB
#define AFX_IDP_E_SETNOTSUPPORTED       0xFEBC
#define AFX_IDP_E_NEEDPROPERTYARRAYINDEX 0xFEBD
#define AFX_IDP_E_SETNOTPERMITTED       0xFEBE
#define AFX_IDP_E_GETNOTSUPPORTEDATRUNTIME 0xFEBF
#define AFX_IDP_E_GETNOTSUPPORTED       0xFEC0
#define AFX_IDP_E_PROPERTYNOTFOUND      0xFEC1
#define AFX_IDP_E_INVALIDCLIPBOARDFORMAT 0xFEC2
#define AFX_IDP_E_INVALIDPICTURE        0xFEC3
#define AFX_IDP_E_PRINTERERROR          0xFEC4
#define AFX_IDP_E_CANTSAVEFILETOTEMP    0xFEC5
#define AFX_IDP_E_SEARCHTEXTNOTFOUND    0xFEC6
#define AFX_IDP_E_REPLACEMENTSTOOLONG   0xFEC7
#define SPVERSION_MASK                  0x0000FF00
//#define SCHAR_MIN                       -128
//#define EOF                             -1
#define USHRT_MAX                       0xffff

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

