//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SigGrphWnd.rc
//
#define IDS_PROJNAME                    100
#define IDR_WMDMLOGGER                  101
#define IDD_DLG_GRAPH_LEFT_TOP          135
#define IDI_ICON_LEFT                   148
#define IDI_ICON_DOWN                   149
#define IDI_ICON_RIGHT                  150
#define IDI_ICON_UP                     151
#define IDS_LOG_SEV_INFO                201
#define IDC_COMBO_DISPLAY               201
#define IDS_LOG_SEV_WARN                202
#define IDC_LIST_SIG_VALUES             202
#define IDS_LOG_SEV_ERROR               203
#define IDC_EDIT_T1                     203
#define IDS_LOG_DATETIME                204
#define IDC_EDIT_T2                     204
#define IDS_LOG_SRCNAME                 205
#define IDC_DMGRAPHCTRL                 205
#define IDC_GRID_COLOR                  206
#define IDC_EDIT_DELTA_T                206
#define IDC_DMGRAPHCTRL1                206
#define IDC_DMGRAPH_CTRL                206
#define IDC_FRAME_COLOR                 207
#define IDB_BMP_GRAPH_ELEMENTS          207
#define IDC_POINT_COLOR                 208
#define IDC_PLOT_COLOR                  208
#define IDC_AXIS_COLOR                  209
#define IDC_COMBO_TYPE                  210
#define IDC_LABEL_COLOR                 210
#define IDR_ICON_GRAPH                  211
#define IDC_COMBO_SYMBOL                212
#define IDC_LINE_COLOR                  214
#define IDC_COMBO_FRAME                 215
#define IDD_DLG_GRAPH_EXPORT            276
#define IDD_DLG_GRAPH_RIGHT_BOTTOM      277
#define IDD_DLG_GRAPH_RIGHT_TOP         278
#define IDD_DLG_GRAPH_WINDOW_CONF       279
#define IDD_DLG_MSG_LIST                280
#define IDS_DEF_LOGFILE                 301
#define IDS_DEF_MAXSIZE                 302
#define IDS_DEF_SHRINKTOSIZE            303
#define IDS_DEF_LOGENABLED              304
#define IDS_MUTEX_TIMEOUT               401
#define IDC_LIST_SIGNALS                1001
#define IDC_BTN_DELETE                  1002
#define IDC_BTN_DELETE_ALL              1003
#define IDC_BTN_RIGHT                   1004
#define IDC_RADIO_AXIS_X                1008
#define IDC_BTN_ENABLE                  1008
#define IDC_RADIO_AXIS_Y                1009
#define IDC_TREE_SIGNAL                 1009
#define IDC_LSTC_GRAPH_ELEMENTS         1010
#define IDC_BTN_UP                      1017
#define IDC_BTN_SAVE_IMAGE              1018
#define IDC_RADIO_AXIS_XY               1019
#define IDC_RADIO_ACTION_MOVE           1020
#define IDC_BTN_LEFT                    1021
#define IDC_BTN_DOWN                    1022
#define IDC_RADIO_ACTION_ZOOM           1025
#define IDC_RADIO_ACTION_TRACK          1026
#define IDC_RADIO_ACTION_NONE           1027
#define IDC_EDIT_CSV_FILE_NAME          1030
#define IDC_BTN_CONFIGURE               1031
#define IDC_EDIT_HTML_FILE_NAME         1031
#define IDC_EDIT_IMAGE_FILE_NAME        1032
#define IDC_BTN_BROWSE_CSV              1033
#define IDC_BTN_BROWSE_HTML             1034
#define IDC_BTN_BROWSE_BMP              1035
#define IDC_BTN_SAVE_CSV                1036
#define IDC_BTN_SAVE_HTML               1037
#define IDC_CHECK_PRINT_REPORT          1038
#define IDC_BTN_EXPORT                  1039
#define IDC_BTN_VISIBLE                 1040
#define IDC_EDIT_RANGE_FROM             1041
#define IDC_EDIT_RANGE_TO               1042
#define IDC_BTN_SET                     1043
#define IDC_BTN_AUTO_FIT                1044
#define IDC_BTN_COPY                    1045
#define IDC_BTN_GRID                    1046
#define IDC_BTN_FIT_ALL                 1048
#define IDC_EDIT_BUFFER_SIZE            1181
#define IDC_EDIT_X_GRIDS                1182
#define IDC_EDIT_DISPLAY_UPDATE         1183
#define IDC_EDIT_Y_GRIDS                1184
#define IDC_BTN_ADD                     1228
#define IDC_CBTN_SET_DEFAULT            1241
#define IDC_GRAPH_CTRL                  1244
#define IDC_WEB_BROWSER                 1245
#define IDC_COMBO_LINE_DISPLAY          1329
