// BusEmulation.idl : IDL source for BusEmulation
//

// This file will be processed by the MIDL tool to
// produce the type library (BusEmulation.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";


[
	object,
	uuid(8B6AC5D7-8591-488F-844B-DC74A2CE704B),
	dual,
	nonextensible,
	helpstring("ISimENG Interface"),
	pointer_default(unique)
]
interface ISimENG : IDispatch{
    [id(1), helpstring("method SendMessage")] HRESULT SendMessage([in] USHORT ClientID, [in] USHORT CurrDataLength, [in] BYTE pbCurrDataByte[128]);
    [id(2), helpstring("method RegisterClient")] HRESULT RegisterClient([in] USHORT Bus, [in] USHORT MaxDataLen, [out] USHORT* ClientID, [out] BSTR* PipeName, [out] BSTR* EventName);
    [id(3), helpstring("method UnregisterClient")] HRESULT UnregisterClient([in] USHORT ClientID);
    [id(4), helpstring("method ConnectNode")] HRESULT ConnectNode([in] USHORT ClientID);
    [id(5), helpstring("method DisconnectNode")] HRESULT DisconnectNode([in] USHORT ClientID);
    [id(6), helpstring("method GetTimeModeMapping")] HRESULT GetTimeModeMapping([out] SYSTEMTIME* CurrSysTime, [out] ULONGLONG* TimeStamp, [out]LARGE_INTEGER* lQueryTickCount);
    [id(7), helpstring("method GetCurrentStatus")] HRESULT GetCurrentStatus([in] USHORT ClientID, [in,out] VARIANT *pNodeStatus);
};
[
	uuid(77E353C7-244B-44DE-B218-9141831EB122),
	version(1.1),
	helpstring("BusEmulation 1.1 Type Library")
]
library BusEmulationLib
{
	importlib("stdole2.tlb");
	[
		uuid(490146BC-A1BA-4EC6-9515-8475D86946A6),		helpstring("SimENG Class")
	]
	coclass SimENG
	{
		[default] interface ISimENG;
	};
};
