/* This file is generated by BUSMASTER */
/* VERSION [1.1] */
/* BUSMASTER VERSION [1.6.5] */
/* PROTOCOL [CAN] */

/* Start BUSMASTER include header */
#include <Windows.h>
#include <struct.h>

/* End BUSMASTER include header */


/* Start BUSMASTER global variable */

/* End BUSMASTER global variable */


/* Start BUSMASTER Function Prototype  */
int Utils_Add(int x, int y);
/* End BUSMASTER Function Prototype  */

/* Start BUSMASTER generated function - OnMsg_All */
void OnMsg_All(STCAN_MSG RxMsg)
{
/* TODO */
}/* End BUSMASTER generated function - OnMsg_All */
/* Start BUSMASTER generated function - OnTimer_TimeCheck_1 */
void OnTimer_TimeCheck_1( )
{
Trace("Time Check Handler");
}/* End BUSMASTER generated function - OnTimer_TimeCheck_1 */
/* Start BUSMASTER generated function - OnKey_a */
void OnKey_a(unsigned char KeyValue)
{
/* TODO */
Utils_Add(5,5);
Trace("Key 'a' is pressed");
}/* End BUSMASTER generated function - OnKey_a */
/* Start BUSMASTER generated function - OnError_Active */
void OnError_Active(SCAN_ERR ErrorMsg)
{
STCAN_MSG sMsg;

// Initialise message structure
sMsg.m_unMsgID = 0x100;              // Message ID
sMsg.m_ucEXTENDED = FALSE;           // Standard Message type
sMsg.m_ucRTR = FALSE;                // Not RTR type
sMsg.m_ucDLC = 8;                    // Length is 8 Bytes
sMsg.m_sWhichBit.m_aulData[0] = 10;  // Lower 4 Bytes
sMsg.m_sWhichBit.m_aulData[1] = 20;  // Upper 4 Bytes
sMsg.m_ucChannel = 1;                // First CAN channel

// Send the message
SendMsg(sMsg);
}/* End BUSMASTER generated function - OnError_Active */
/* Start BUSMASTER generated function - OnDLL_Load */
void OnDLL_Load()
{
Trace("DLL _Load");

}/* End BUSMASTER generated function - OnDLL_Load */
/* Start BUSMASTER generated function - OnDLL_Unload */
void OnDLL_Unload()
{
Trace("DLL _UnLoad");

}/* End BUSMASTER generated function - OnDLL_Unload */
/* Start BUSMASTER generated function - Utils_Add */
int Utils_Add(int x, int y)
{
int sum = 0;
sum = x+y;
return sum;
}/* End BUSMASTER generated function - Utils_Add */
