/* This file is generated by BUSMASTER */
/* VERSION [1.1] */
/* BUSMASTER VERSION [1.6.4] */
/* PROTOCOL [J1939] */

/* Start J1939 include header */
#include <Windows.h>
#include <Struct_J1939.h>

/* End J1939 include header */


/* Start J1939 global variable */

/* End J1939 global variable */


/* Start J1939 Function Prototype  */
/* End J1939 Function Prototype  */

/* Start J1939 generated function - OnPGN_All */
void OnPGN_All(STJ1939_MSG* RxMsg)
{
if ( RxMsg->m_sMsgProperties.m_eDirection == DIR_RX && RxMsg->m_sMsgProperties.m_byChannel == 1
     && RxMsg->m_sMsgProperties.m_eType == MSG_TYPE_DATA )
{
	/* Declarations */
	UINT64 unECUName = 0x8000000000000001;
	UINT ReturnValue = 0;
	/* Go offline */
	ReturnValue = GoOffline();

	/* Go online */
	ReturnValue = GoOnline();

	/* Claim address 0x5 on channel 1 */
	ReturnValue = ClaimAddress(0x5,0x1);

	/* send message */
	RxMsg->m_sMsgProperties.m_uExtendedID.m_unExtID = 0xCF004EE;
	RxMsg->m_sMsgProperties.m_eType = MSG_TYPE_BROADCAST;
	ReturnValue = SendMsg(RxMsg);

	/* Request PGN */
	ReturnValue = RequestPGN(0xD700,0xFF,1);

	/* Send acknowledgement message */
	ReturnValue = SendAckMsg(RxMsg->m_sMsgProperties.m_uExtendedID.m_s29BitId.m_uPGN.m_unPGN, 0,0x00, 1);


	/* Request address */
	ReturnValue = RequestAddress(1);

	/* Command Monitor node address */
	ReturnValue = CommandAddress(unECUName, 0x0, 1);

	/* Set Timeouts */
	ReturnValue = SetTimeout(0,  100); //Tb
	ReturnValue = SetTimeout(1,  200); //Tr
	ReturnValue = SetTimeout(2,  500); //Th
	ReturnValue = SetTimeout(3,  750); //T1
	ReturnValue = SetTimeout(4, 1250); //T2
	ReturnValue = SetTimeout(5, 1250); //T3
	ReturnValue = SetTimeout(6, 1050); //T4
}
}/* End J1939 generated function - OnPGN_All */
/* Start J1939 generated function - OnEvent_AddressClaim */
void OnEvent_AddressClaim(BYTE byAddress)
{
/* Declarations */
UINT ReturnValue  = 0;
char strTimerVal[] = "OnTimer_Repeat_1000";
char strLogData[]  = "Sample Log Data";
char strDllName[]  = "SampleJ1939.dll";
HANDLE hNode = 0;

Trace("Start of J1939 API calls");
/* Enable all handlers */
ReturnValue = EnableAllHandlers(TRUE);

/* Disable message transmission from node */
ReturnValue = EnableDisableMsgTx(FALSE);

/* Enable message transmission from node */
ReturnValue = EnableDisableMsgTx(TRUE);

/* Enable key handlers */
ReturnValue = EnableKeyHandlers(TRUE);

/* Enable msg handlers */
ReturnValue = EnableMsgHandlers(TRUE);

/* Set Timer value */
ReturnValue = SetTimerVal(strTimerVal, 5000);

/* Enable Logging */
ReturnValue = EnableLogging();

if (ReturnValue == 1)
{
	/* WriteToLogFile */
	ReturnValue = WriteToLogFile(strLogData);
	Trace("Written to Log file!");

	/* Disable Logging */
	ReturnValue = DisableLogging();
}

/* Get Dll Handle */
hNode = GetDllHandle(strDllName);

/* start timer in different modes */
ReturnValue = StartTimer(strTimerVal, 1);
ReturnValue = StartTimer(strTimerVal, 0);

/* Stop Timer */
ReturnValue = StopTimer(strTimerVal);

Trace("End of J1939 API calls");
}/* End J1939 generated function - OnEvent_AddressClaim */
/* Start J1939 generated function - OnTimer_Repeat_1000 */
void OnTimer_Repeat_1000( )
{
Trace("On Timer");
}/* End J1939 generated function - OnTimer_Repeat_1000 */
/* Start J1939 generated function - OnEvent_DataConf */
void OnEvent_DataConf(UINT32 unPGN, BYTE bySrc, BYTE byDest, BOOL bSuccess)
{
Trace("Data confirmation event executed!");
}/* End J1939 generated function - OnEvent_DataConf */
