//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NodeSimEx.rc
//
#define IDC_CBTN_KEY_APPLY              3
#define IDR_BMP_FUNC_EDITOR             135
#define IDM_FNVIEW_CTXMENU              137
#define IDD_DLG_DEFINE_UTILITY_FN       138
#define IDM_FUNC_EDITOR                 139
#define IDD_DLG_SELECT_FNS              153
#define IDD_DLG_ERROR_HANDLER           185
#define IDI_ICON_FN_EDITOR              219
#define IDI_ICON_SIMSYS_CONFIG          224
#define IDD_NODE_DEATILS                233
#define IDD_DLG_DLL_HANDLER             273
#define IDD_DLG_MSG_HANDLERS            274
#define IDD_DLG_KEY_VALUE               286
#define IDD_DLG_DEFINE_TIMER_HANDLER    287
#define IDD_DLG_INCLUDE_HEADERS         288
#define IDC_BTN_BROWSE                  1001
#define IDC_RBTN_CHANNEL1               1007
#define IDC_RBTN_CHANNEL2               1008
#define IDC_EDIT_NODE_FILE_PATH         1010
#define IDC_CHKB_WANT_STRUCTURE         1028
#define IDC_COMB_FN_RETURN_TYPE         1029
#define IDC_EDIT_FN_PROTO               1030
#define IDC_STAT_RETURN_TYPE            1031
#define IDC_STAT_FN_PROTO               1032
#define IDC_CBTN_OK                     1042
#define IDC_CBTN_CANCEL                 1043
#define IDC_EDIT_TIMER_FUNCTION_NAME    1044
#define IDC_EDIT_TIMER_VALUE            1045
#define IDC_STAT_TIMER_FUNCTION         1046
#define IDC_STAT_MILI_SECOND            1047
#define IDC_STAT_TIMER_VALUE            1048
#define IDC_EDIT_FILENAME               1049
#define IDC_STAT_INCLUDE_HEADER         1050
#define IDC_CBTN_BROWSE                 1051
#define IDC_LSTB_FUNCTIONS              1068
#define IDC_LSTB_SIGNAL                 1069
#define IDC_LSTC_MSGS                   1070
#define IDC_STAT_KEY                    1077
#define IDC_EDIT_MSG_HANDLER_ID         1155
#define IDC_CHKB_ERROR_ACTIVE_HANDLER   1155
#define IDC_CHKB_ERROR_PASSIVE_HANDLER  1156
#define IDC_CHKB_WARNING_LIMIT_HANDLER  1157
#define IDC_CHKB_BUS_OFF_HANDLER        1158
#define IDC_CHKB_ERROR_FRAME_HANDLER    1159
#define IDC_EDIT_MSG_HANDLER_ID_FROM    1160
#define IDC_EDIT_MSG_HANDLER_ID_TO      1161
#define IDC_CHKB_DLL_LOAD_HANDLER       1164
#define IDC_CHKB_DLL_UNLOAD_HANDLER     1165
#define IDC_CBTN__MSG_OK                1167
#define IDC_CBTN__MSG_CANCEL            1168
#define IDC_LSTB_MSG_HANDLER_LIST       1169
#define IDC_RBTN_MSG_NAME               1170
#define IDC_RBTN_MSG_ID                 1171
#define IDC_RBTN_MSG_RANGE              1172
#define IDC_RBTN_MSG_ALL                1173
#define IDC_CBTN_MSG_HANDLDER_APPLY     1174
#define IDC_CBTN__ERROR_OK              1176
#define IDC_CBTN__ERROR_CANCEL          1177
#define IDC_CBTN__DLL_OK                1178
#define IDC_CBTN__DLL_CANCEL            1179
#define IDC_EDIT_UTILS_FN               1184
#define IDC_STAT_NODE_NAME              1268
#define IDC_EDIT_ANODE_NAME             1278
#define IDC_STAT_SELCHANNEL             1284
#define MyShortcutmenu                  3004
#define IDR_MENU1                       3005
#define IDC_EDIT_ADDRESS                4000
#define IDC_EDIT_ECU_NAME               4001
#define IDD_EVENT_HANDLER               4001
#define IDC_STATIC_ECU_NAME             4002
#define IDD_DLG_BUSEV_HANDLER           4002
#define IDC_STATIC_ADDRESS              4003
#define IDC_STATIC_MSG_ID               4004
#define IDD_DLG_ERR_HANDLER_LIN         4004
#define IDC_STATIC_MSG_ID_RANGE         4005
#define IDC_STATIC_DB_MSG_LIST          4006
#define IDM_NODE_MENU                   4006
#define IDC_CHECK_DATA_CONF             4007
#define IDC_CHECK_ADDRESS_CLAIM         4008
#define IDB_NODE_SIMULATION             4010
#define IDC_CHKB_BUSEV_CONNECT_HANDLER  4011
#define IDOK_LIN                        4011
#define IDB_NODE_SIMULATION_HOT         4011
#define IDC_CHKB_BUSEV_DISCONNECT_HANDLER 4012
#define IDB_NODE_SIMULATION_DISABLED    4012
#define IDC_CHKB_BUSEV_PRECONNECT_HANDLER 4013
#define IDI_ICON_NODE_ENABLED           4013
#define IDCANCEL_LIN                    4014
#define IDI_ICON_NODE_DISABLED          4014
#define IDC_CHK_START_CYCLE_ALL         4015
#define IDC_CHK_ERR_CHECKSUM_LIN        4015
#define IDC_CMB_CHANNEL                 4015
#define IDB_NODE_SIMULATION_TREEVIEW    4015
#define IDC_CHK_ERR_FRAME_LIN           4016
#define IDC_COMBO1                      4016
#define IDC_CMB_CHANNEL_SEL             4016
#define IDC_STATIC_CHANNEL              4020
#define IDC_CHK_ERR_SLAVE_NO_RESP_LIN   4017
#define IDC_CHK_ERR_Sync                4018
#define IDC_CHK_ERR_SLAVE_TIMEOUT_LIN   4019
#define IDD_MSG_SG_DLG                  5000
#define ID_FUNCTIONEDITOR_SAVE          35000
#define ID_ROOTMENU_ADD                 35001
#define ID_ROOTMENU_BUILDALL            35002
#define ID_ROOTMENU_ENABLEALL           35003
#define ID_ROOTMENU_DISABLEALL          35004
#define ID_ROOTMENU_REMOVEALL           35005
#define ID_RYUJ_SJ                      35006
#define ID_NODEMENU_EDIT                35007
#define ID_NODEMENU_CONFIGURE           35008
#define ID_NODEMENU_BUILD               35009
#define ID_NODEMENU_ENABLE              35010
#define ID_NODEMENU_REMOVE              35011
#define IDM_EDIT_NODE                   35012
#define IDM_CONFIG_NODE                 35013
#define IDM_BUILD_NODE                  35014
#define IDM_REMOVE_NODE                 35016
#define IDM_ADD_NODE                    35017
#define IDR_NODE_SIMULATION             35022
#define IDM_ADD_HAND                    35023
#define IDM_DEL_HAND                    35024
#define IDM_EDIT_HAND                   35025
#define IDM_ROOT_MENU                   35026
#define IDM_CONTEXT_INSERTFUNCTION      61449
#define IDM_CONTEXT_INSERTMESSAGE       61450
#define IDM_CONTEXT_INSERTSIGNAL        61451

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4021
#define _APS_NEXT_COMMAND_VALUE         35026
#define _APS_NEXT_CONTROL_VALUE         4035
#define _APS_NEXT_SYMED_VALUE           4000
#endif
#endif
