//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NodeSimEx.rc
//
#define IDC_CBTN_KEY_APPLY              3
#define IDR_BMP_FUNC_EDITOR             135
#define IDM_FNVIEW_CTXMENU              137
#define IDD_DLG_DEFINE_UTILITY_FN       138
#define IDM_FUNC_EDITOR                 139
#define IDD_DLG_SET_RESET_TIMER         152
#define IDD_DLG_SELECT_FNS              153
#define IDD_DLG_ERROR_HANDLER           185
#define IDI_ICON_FN_EDITOR              219
#define IDM_SIMSYS_OPRNS                221
#define IDM_SIMSYS_CONFIGMENU           222
#define IDM_NODE_OPRNS                  223
#define IDI_ICON_SIMSYS_CONFIG          224
#define IDD_DLG_SIMSYSDETVIEW           229
#define IDD_NODE_DEATILS                233
#define IDD_DLG_DLL_HANDLER             273
#define IDD_DLG_MSG_HANDLERS            274
#define IDD_DLG_KEY_VALUE               286
#define IDD_DLG_DEFINE_TIMER_HANDLER    287
#define IDD_DLG_INCLUDE_HEADERS         288
#define IDC_CHCK_MONOSHOT               300
#define IDC_LSTC_TIMER_HANDLER          301
#define IDC_BTN_BROWSE                  1001
#define IDC_BUTTON_OPENFILE             1001
#define IDC_BUTTON_EDITFILE             1002
#define IDC_BUTTON_BUILD                1003
#define IDC_BTN_CLEAR                   1004
#define IDC_BUTTON_BUILDANDLOAD         1004
#define IDC_BUTTON_LOAD                 1005
#define IDC_RBTN_CHANNEL1               1007
#define IDC_RBTN_CHANNEL2               1008
#define IDC_EDIT_DLL_PATH               1010
#define IDC_EDIT_NODE_NAME              1011
#define IDC_EDIT_PREF_ADRES             1012
#define IDC_BUTTON_ENABLEHANDLER        1014
#define IDC_BUTTON_ENABLEALLHANDLERS    1015
#define IDC_CHKB_WANT_STRUCTURE         1028
#define IDC_COMB_FN_RETURN_TYPE         1029
#define IDC_EDIT_FN_PROTO               1030
#define IDC_STAT_RETURN_TYPE            1031
#define IDC_STAT_FN_PROTO               1032
#define IDC_CBTN_OK                     1042
#define IDC_CBTN_CANCEL                 1043
#define IDC_EDIT_TIMER_FUNCTION_NAME    1044
#define IDC_EDIT_TIMER_VALUE            1045
#define IDC_STAT_TIMER_FUNCTION         1046
#define IDC_STAT_MILI_SECOND            1047
#define IDC_STAT_TIMER_VALUE            1048
#define IDC_EDIT_FILENAME               1049
#define IDC_STAT_INCLUDE_HEADER         1050
#define IDC_CBTN_BROWSE                 1051
#define IDC_LSTB_FUNCTIONS              1068
#define IDC_LSTB_SIGNAL                 1069
#define IDC_LSTC_MSGS                   1070
#define IDC_STAT_KEY                    1077
#define IDC_EDIT_MSG_HANDLER_ID         1155
#define IDC_CHKB_ERROR_ACTIVE_HANDLER   1155
#define IDC_CHKB_ERROR_PASSIVE_HANDLER  1156
#define IDC_CHKB_WARNING_LIMIT_HANDLER  1157
#define IDC_CHKB_BUS_OFF_HANDLER        1158
#define IDC_CHKB_ERROR_FRAME_HANDLER    1159
#define IDC_EDIT_MSG_HANDLER_ID_FROM    1160
#define IDC_EDIT_MSG_HANDLER_ID_TO      1161
#define IDC_CHKB_DLL_LOAD_HANDLER       1164
#define IDC_CHKB_DLL_UNLOAD_HANDLER     1165
#define IDC_CBTN__MSG_OK                1167
#define IDC_CBTN__MSG_CANCEL            1168
#define IDC_LSTB_MSG_HANDLER_LIST       1169
#define IDC_RBTN_MSG_NAME               1170
#define IDC_RBTN_MSG_ID                 1171
#define IDC_RBTN_MSG_RANGE              1172
#define IDC_RBTN_MSG_ALL                1173
#define IDC_CBTN_MSG_HANDLDER_APPLY     1174
#define IDC_CBTN__ERROR_OK              1176
#define IDC_CBTN__ERROR_CANCEL          1177
#define IDC_CBTN__DLL_OK                1178
#define IDC_CBTN__DLL_CANCEL            1179
#define IDC_EDIT_UTILS_FN               1184
#define IDC_LSTC_HANDLER_DETAILS        1226
#define IDC_BTN_OK                      1227
#define IDC_STAT_NODE_DETAILS           1266
#define IDC_EDIT_FILE_NAME              1267
#define IDC_STAT_NODE_NAME              1268
#define IDC_STAT_FILE_NAME              1269
#define IDC_STAT_FILEGRP                1270
#define IDC_STAT_HANGROUP               1271
#define IDC_LSTC_HANVAL                 1272
#define IDC_STAT_HANDESC                1273
#define IDC_STAT_NODE_LIST              1275
#define IDC_COMB_NODENAME               1276
#define IDC_EDIT_ANODE_NAME             1278
#define IDC_STAT_SELCHANNEL             1284
#define IDC_BTN_APPLY                   1300
#define MyShortcutmenu                  3004
#define IDR_MENU1                       3005
#define IDC_EDIT_ADDRESS                4000
#define IDC_EDIT_ECU_NAME               4001
#define IDD_EVENT_HANDLER               4001
#define IDC_STATIC_ECU_NAME             4002
#define IDC_STATIC_ADDRESS              4003
#define IDC_STATIC_MSG_ID               4004
#define IDC_STATIC_MSG_ID_RANGE         4005
#define IDC_STATIC_DB_MSG_LIST          4006
#define IDC_CHECK_DATA_CONF             4007
#define IDC_CHECK_ADDRESS_CLAIM         4008
#define IDC_STATIC_PREF_ADRES           4009
#define IDC_EDIT_ECUNAME                4010
#define IDD_MSG_SG_DLG                  5000
#define ID_FUNCTIONEDITOR_SAVE          32772
#define ID_RYUJ_SJ                      32778
#define IDM_ADD_HAND                    32861
#define IDM_DEL_HAND                    32862
#define IDM_EDIT_HAND                   32914
#define IDM_NEW_SIMSYS                  32960
#define IDM_ADD_SIMSYS                  32961
#define IDM_DELETE_ALL_SIMSYS           32962
#define IDM_SIMSYS_SAVE                 32963
#define IDM_SIMSYS_SAVEAS               32965
#define IDM_SIMSYS_DELETESIMULATEDSYSTEM 32967
#define IDM_SIMSYS_ADDNODE              32970
#define IDM_SIMSYS_DELETEALLNODES       32972
#define IDM_SIMSYS_ALLHANDLERS          32974
#define IDM_SIMSYS_ALLKEYHANDLERS       32976
#define IDM_SIMSYS_ALLMSGHANDLERS       32979
#define IDM_SIMSYS_ALLERRORHANDLERS     32981
#define IDM_SIMSYS_ALLTIMERHANDLERS     32983
#define IDM_EDIT_NODE                   32984
#define IDM_DELETE_NODE                 32986
#define IDM_ALL_NODE_HANDLERS           32987
#define IDM_NODE_KEYHANDLERS            32989
#define IDM_NODE_MESSAGEHANDLERS        32991
#define IDM_NODE_ERRORHANDLERS          32993
#define IDM_NODE_TIMERHANDLERS          32995
#define IDM_SIMSYS_BUILDALL             32998
#define IDM_SIMSYS_LOADALL              33002
#define IDM_SIMSYS_UNLOADALL            33004
#define IDM_SAVE_ALL_SIMSYS             33006
#define IDM_CONTEXT_INSERTFUNCTION      61449
#define IDM_CONTEXT_INSERTMESSAGE       61450
#define IDM_CONTEXT_INSERTSIGNAL        61451
