//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BUSMASTER.rc
//
#define IDB_CONTINUE                    1
#define IDC_CBTN_UPDATE                 3
#define IDC_CBTN_KEY_APPLY              3
#define IDC_BUT_REMOVE                  3
#define IDC_BTN_ADD_FILTER_TO_LIST      3
#define IDC_BTN_DELETE_FILE             4
#define IDC_CBTN_CANCELEXPORT           4
#define IDC_BUT_SELECT                  5
#define IDB_LICENSE                     9
#define IDB_LICENSE2                    10
#define IDB_OK                          10
#define IDD_ABOUTBOX                    100
#define IDD_DLG_MSGSGDETVIEW            101
#define IDR_BMP_SPLASH                  102
#define IDR_BMP_SPLASH_SCREEN           102
#define IDD_DLG_SEND_DUMMY_MSG          103
#define IDD_PPAGE_MESSAGE               106
#define IDB_LICENSEDLG                  110
#define IDR_CAN_MONITOR                 111
#define IDR_BUSMASTERINTERFACE          112
#define IDR_MAINFRAME                   128
#define IDR_NEWEDTYPE                   129
#define IDR_PGM_EDTYPE                  129
#define IDR_MENU_SIGNAL_WATCH           130
#define IDM_MENU_SIGNAL_WATCH           130
#define IDS_ERROR_LOCK_KEY_INCORRECT    130
#define IDD_DLG_SIGNAL                  131
#define IDS_ERROR_VER_MISMATCH          131
#define IDR_BMP_MSGSGDB                 132
#define IDD_DLG_SIGNALSDETAILS          133
#define IDR_BMP_CHK_UCHK                134
#define IDM_SG_OPN_MENU                 134
#define IDD_DLG_GRAPH_LEFT_TOP          135
#define IDM_MSG_OPN_MENU                136
#define IDD_DLG_VALUE_DESCRIPTOR        136
#define IDD_DLG_GLOBAL_VARIABLE         137
#define IDD_DLG_MSGID_ATTRIB            140
#define IDD_DLG_CANID_LIST              141
#define IDD_DLG_LOGREPLAY               146
#define IDD_MESSAGE_DIALOG              147
#define IDD_DLG_MSG_SG_LIST             148
#define IDI_ICON_LEFT                   148
#define IDD_DLG_DRIVERINFO              149
#define IDI_ICON_DOWN                   149
#define IDI_ICON_RIGHT                  150
#define IDI_ICON_UP                     151
#define IDD_DLG_CONFIG_MSG_LOG          151
#define IDD_DLG_EXPORT_LOG_FILE         155
#define IDI_ICO_LOG                     156
#define IDD_DLG_SIGNAL_MATRIX           157
#define IDD_DIALOG1                     158
#define IDD_DLG_SEND_MULTI_MSG          158
#define IDI_ICON_SEND_MSG               163
#define IDM_SEND_OPRNS                  164
#define IDM_CONFIG_MSG_BLOCK            165
#define IDB_BMP_DISCONNECT              166
#define IDB_BMP_CONNECT                 167
#define IDB_CAN_DATABASE                167
#define IDB_BMP_SEND_MULTI_MSGS         168
#define IDB_BMP_TOOLBAR_DISCONNECT      174
#define IDB_BMP_TOOLBAR_CONNECT         175
#define IDB_BMP_COPYRIGHT               184
#define IDR_ICON_ERROR_ACTIVE           189
#define IDR_ICON_WARNING_LIMIT          190
#define IDR_ICON_ERROR_PASSIVE          191
#define IDR_ICON_BUS_OFF                192
#define IDD_DLG_NETWORK_STATISTICS      193
#define IDI_ICON_MSGWND                 195
#define IDI_ICO_WRITE                   196
#define IDM_MENU_TIMEMODE               198
#define IDD_DLG_INTERPRET_MSG           199
#define IDD_DLG_WAVEFORM_CONFIG         200
#define IDM_MENU_MSG_OPRN               202
#define IDR_BMP_MSG_SIG_WATCH           203
#define IDR_BMP_NET                     204
#define IDD_DLG_MSG_BUFFER_CONGIF       205
#define IDI_ICON_TRANSPERENT            206
#define IDC_GRID_COLOR                  206
#define IDC_FRAME_COLOR                 207
#define IDR_ICON_GRAPH                  207
#define IDB_BMP_GRAPH_ELEMENTS          207
#define IDC_POINT_COLOR                 208
#define IDC_PLOT_COLOR                  208
#define IDC_AXIS_COLOR                  209
#define IDC_COMBO_TYPE                  210
#define IDC_LABEL_COLOR                 210
#define IDI_ICO_SEND_MSG                210
#define IDR_BMP_CHECKBOX                211
#define IDM_OPERATION_LIST              211
#define IDC_COMBO_SYMBOL                212
#define IDC_LINE_COLOR                  214
#define IDB_BMP_FILTER                  214
#define IDC_COMBO_FRAME                 215
#define IDD_DLG_MSG_DISPLAY_FILTER      215
#define IDB_BMP_PROPERTIES              215
#define IDD_DLG_INTERPRETED_MSG         217
#define IDI_ICO_DB_EDITOR               220
#define IDD_DLG_TIME_DELAY              221
#define IDD_NODE_DETAILS                230
#define IDD_DLG_DISSOCIATE_DB           234
#define IDR_MENU2                       237
#define IDR_NODE_SIMULATION             238
#define IDB_NODE_SIMULATION             240
#define IDB_NODE_SIMULATION_HOT         241
#define IDB_NODE_SIMULATION_DISABLED    242
#define IDD_DLG_MSG_FILTER_LIST         252
#define IDB_BITMAP1                     263
#define IDI_ICON1                       264
#define IDI_ICON_PLUS                   264
#define IDB_BITMAP2                     266
#define IDR_TLB_SIGNAL_GENERATION       267
#define IDD_DLG_ENTER_SIGNAL_VALUES     271
#define IDB_BITMAP3                     271
#define IDD_DLG_PROPERTIES              272
#define IDR_TOOLBAR1                    272
#define IDR_TOOLBAR2                    274
#define IDD_DLG_WND_NOTIFIC             275
#define IDB_BITMAP4                     275
#define IDD_DLG_GRAPH_EXPORT            276
#define IDR_TOOLBAR3                    276
#define IDR_TLB_CONFIGURE               276
#define IDD_DLG_GRAPH_RIGHT_BOTTOM      277
#define IDD_DLG_GRAPH_RIGHT_TOP         278
#define IDB_CONFIGURE                   278
#define IDD_DLG_GRAPH_WINDOW_CONF       279
#define IDB_CONFIGURE_HOT               279
#define IDD_DLG_MSG_LIST                280
#define IDB_BITMAP5                     280
#define IDB_CONFIGURE_DISABLED          280
#define IDB_BITMAP6                     283
#define IDD_DLG_LOG_FILE_EXPORT         285
#define IDB_BITMAP7                     285
#define IDD_TIMEOUT                     289
#define IDD_DIALOG_CONFIG_SIG_GRPH_WND  290
#define IDR_CAN_DATABASE                291
#define IDB_CAN_DATABASE_HOT            294
#define IDB_BITMAP8                     295
#define IDB_CAN_DATABASE_DISABLED       295
#define IDI_ICON3                       297
#define IDI_ICON_HELP                   297
#define IDI_ICON2                       298
#define IDI_ICON_ABOUT                  298
#define IDI_ICON_CASCADE                299
#define IDC_CHCK_MONOSHOT               300
#define IDI_ICON4                       300
#define IDI_ICON_TILE                   300
#define IDC_LSTC_TIMER_HANDLER          301
#define IDB_MAINFRAME                   302
#define IDB_MAINFRAME_HOT               303
#define IDB_MAINFRAME_DISABLED          304
#define IDB_MAINFRAMEDSC                305
#define IDB_MAINFRAMEDSC_HOT            306
#define IDB_MAINFRAMEDSC_DISABLED       307
#define ID_DISCONNECT                   308
#define IDR_MESSAGE_WINDOW_TEXT         309
#define IDI_ICON_BLANK                  310
#define IDI_ICON_MINUS                  311
#define IDB_HDRDOWN                     312
#define IDB_HDRUP                       313
#define IDR_MSG_WND                     314
#define IDB_MSG_WND                     315
#define IDB_MSG_WND_HOT                 316
#define IDB_MSG_WND_DISABLED            317
#define IDC_EDIT_SIGNALNAME             1000
#define IDC_EDIT_BAUD_RATE              1000
#define IDC_EDIT_SGNAME                 1000
#define IDC_STAT_SIGANLNAME             1001
#define IDC_EDIT_BTR0                   1001
#define IDC_SPIN_SGLENGTH               1001
#define IDC_LIST_SIGNALS                1001
#define IDC_BUTTON1                     1001
#define IDC_BTN_BROWSE                  1001
#define IDC_BUTTON_OPENFILE             1001
#define IDC_OK                          1001
#define IDC_STAT_SIGNALLENGTH           1002
#define IDC_EDIT_BTR1                   1002
#define IDC_SPIN_BYINDEX                1002
#define IDC_BUTTON17                    1002
#define IDC_BTN_DELETE                  1002
#define IDC_LIST3                       1002
#define IDC_LSTC_SELECTED_FILTERS       1002
#define IDC_BTN_FILTER                  1002
#define IDC_EDIT_LOG_FILE_NAME          1002
#define IDC_BUTTON_EDITFILE             1002
#define IDC_SPIN_LENGTH                 1003
#define IDC_EDIT_FACTOR                 1003
#define IDC_BUTTON18                    1003
#define IDC_BTN_DELETE_ALL              1003
#define IDC_BUTTON5                     1003
#define IDC_BTN_LOG_BROWSE              1003
#define IDC_BUTTON_BUILD                1003
#define IDC_STATIC_BMP                  1003
#define IDC_EDIT_LENGTH                 1004
#define IDC_EDIT_UNIT                   1004
#define IDC_BTN_RIGHT                   1004
#define IDC_COMB_MSG_ID_FROM            1004
#define IDC_BTN_CLEAR                   1004
#define IDC_COMBO_TRIGGER_START         1004
#define IDC_LST_SELECTED                1004
#define IDC_BUTTON_BUILDANDLOAD         1004
#define IDB_PICCTRL                     1004
#define IDC_STAT_BYTE_INDEX             1005
#define IDC_EDIT_MAX                    1005
#define IDC_BTN_SELECT                  1005
#define IDC_BUTTON_LOAD                 1005
#define IDC_LOCKING_KEY                 1005
#define IDC_STAT_STARTBIT               1006
#define IDC_EDIT_MIN                    1006
#define IDC_BUTTON3                     1006
#define IDC_BTN_MOVE_UP                 1006
#define IDC_EDIT_FILE_PATH              1006
#define IDC_EDIT_REPLAY_FILE_NAME       1006
#define IDC_BTN_REMOVE                  1006
#define IDC_STAT_ACCEPTANCE             1007
#define IDC_SPIN_BIT                    1007
#define IDC_EDIT_NET_NAME               1007
#define IDC_BUTTON4                     1007
#define IDC_RADIO1                      1007
#define IDC_BTN_MOVE_DOWN               1007
#define IDC_RADIO_TIME_MODE             1007
#define IDC_CHANNEL1                    1007
#define IDC_RBTN_CHANNEL1               1007
#define IDC_RADIOCYCLIC                 1007
#define IDC_EDIT_ACCEPTANCE_MASK        1008
#define IDC_COMB_SGTYPE                 1008
#define IDC_EDIT_FIRMWARE               1008
#define IDC_BUTTON21                    1008
#define IDC_RADIO_AXIS_X                1008
#define IDC_BTN_ENABLE                  1008
#define IDC_RADIO2                      1008
#define IDC_COMB_MSG_ID_TO              1008
#define IDC_RADIO_TIME_MODE1            1008
#define IDC_CHANNEL2                    1008
#define IDC_RBTN_CHANNEL2               1008
#define IDC_RADIOMONOSHOT               1008
#define IDC_RQST_ADDRESS                1008
#define IDC_EDIT_ACCEPTANCE_CODE        1009
#define IDC_RADIO_AXIS_Y                1009
#define IDC_TREE_SIGNAL                 1009
#define IDC_RADIO3                      1009
#define IDC_CHECK1                      1009
#define IDC_COMB_MSG_ID_TYPE            1009
#define IDC_RADIO_TIME_MODE2            1009
#define IDC_CHK_RETAIN_RECORDED_DELAY   1009
#define IDC_LST_AVAILABLE               1009
#define IDC_STATIC_LOCK1                1009
#define IDC_CMD_ADDRESS                 1009
#define IDC_CHECK_BROADCAST             1009
#define IDC_STAT_MASK                   1010
#define IDC_COMBO_BUS_TYPE              1010
#define IDC_EDIT_VALUE_DESC             1010
#define IDC_LSTC_GRAPH_ELEMENTS         1010
#define IDC_COMBO1                      1010
#define IDC_COMB_CHANNEL_ID             1010
#define IDC_RADIO4                      1010
#define IDC_EDIT2                       1010
#define IDC_COMB_MSG_TYPE               1010
#define IDC_RADIO_NUM_MODE              1010
#define IDC_EDIT_MSG_DELAY              1010
#define IDC_EDIT_DLL_PATH               1010
#define IDC_COMBO_MSGS                  1010
#define IDC_COMBO_NODE                  1010
#define IDC_EDIT_RESPONSE               1010
#define IDC_STAT_MASK2                  1011
#define IDC_LSTC_SIGNAL_DETAILS         1011
#define IDC_EDIT_VAL                    1011
#define IDC_RADIO5                      1011
#define IDC_EDIT3                       1011
#define IDC_COMB_MSG_DIRECTION          1011
#define IDC_RADIO_NUM_MODE1             1011
#define IDC_EDIT_CYCLE_DELAY            1011
#define IDC_BTN_CSV_BROWSE              1011
#define IDC_EDIT_NODE_NAME              1011
#define IDC_SEND                        1011
#define IDC_EDIT_HOLDING                1011
#define IDC_LSTC_BTR_LIST               1012
#define IDC_SPIN_MSG_LEN                1012
#define IDC_RADIO6                      1012
#define IDC_COMB_MSG_CHANNEL            1012
#define IDC_RADIO_REPLAY_MODE_MONO      1012
#define ID_CONVERT                      1012
#define IDC_CLAIM_ADDRESS               1012
#define IDC_STAT_BAUD_RATE              1013
#define IDC_EDIT_MSG_LENGTH             1013
#define IDC_RADIO7                      1013
#define IDC_RADIO_REPLAY_MODE_CYCLIC    1013
#define IDC_RADIO_TPF                   1013
#define IDC_STAT_KBPS                   1014
#define IDC_STAT_MSG_FRM_FMT            1014
#define IDC_BUTTON2                     1014
#define IDC_BTN_UPDATE                  1014
#define IDC_COMBO7                      1014
#define IDC_CHECK2                      1014
#define IDC_COMBO_TRIGGER_STOP          1014
#define IDC_CHK_INTERACTIVE             1014
#define IDC_BUTTON_ENABLEHANDLER        1014
#define IDC_BUTTON_GRP_DISP_CONFIG      1014
#define IDC_COMBO_CHANNEL               1014
#define IDC_CHECK_RESPONSE              1014
#define IDC_STAT_BUAD_RATE              1015
#define IDC_RBTN_STD                    1015
#define IDC_BUTTON6                     1015
#define IDC_BTN_CLOSE                   1015
#define IDC_CHECK3                      1015
#define IDC_CHECK_ENABLE_LOG_CONNECT    1015
#define IDC_BUTTON_ENABLEALLHANDLERS    1015
#define IDC_CHECK_CYCLIC                1015
#define IDC_CHECK_HOLDING               1015
#define IDC_STAT_BTR0                   1016
#define IDC_RBTN_EXTDED                 1016
#define IDC_STAT_BUAD_RATE2             1016
#define IDC_EDIT_DATA                   1016
#define IDC_STAT_BTR1                   1017
#define IDC_STAT_SIGNAL_VAL             1017
#define IDC_BTN_UP                      1017
#define IDC_EDIT_BRP                    1018
#define IDC_STAT_DESC                   1018
#define IDC_LSTC_HW_LIST                1018
#define IDC_BTN_SAVE_IMAGE              1018
#define IDC_COMB_SAMPLING               1019
#define IDC_STAT_SGNAME                 1019
#define IDC_EDIT_MSG_NAME               1019
#define IDC_EDIT_DRIVER_ID              1019
#define IDC_RADIO_AXIS_XY               1019
#define IDC_COMB_CLOCK                  1020
#define IDC_STAT_BYINDEX                1020
#define IDC_BUT_BLINK                   1020
#define IDC_RADIO_ACTION_MOVE           1020
#define IDC_BUTTON_SELECTONE            1020
#define IDC_STAT_STBIT                  1021
#define IDC_BTN_LEFT                    1021
#define IDC_COMB_PROPDELAY              1021
#define IDC_STAT_CLOCK                  1022
#define IDC_STAT_SGLEN                  1022
#define IDC_STAT_MSG_LISTGP             1022
#define IDC_BTN_DOWN                    1022
#define IDC_COMB_SGVALUE                1023
#define IDC_EDIT_BYINDEX                1023
#define IDC_STAT_SG_LISTGP              1023
#define IDC_COMB_SAMPLING3              1023
#define IDC_COMB_SJW                    1023
#define IDC_EDIT_SGLEN                  1024
#define IDC_COMB_VAR_TYPE               1024
#define IDC_BUTTON_REMOVEONE            1024
#define IDC_EDIT_STBIT                  1025
#define IDC_STAT_VAR_TYPE               1025
#define IDC_RADIO_ACTION_ZOOM           1025
#define IDC_STAT_FACTOR                 1026
#define IDC_STAT_GLOBAL_NAME            1026
#define IDC_RADIO_ACTION_TRACK          1026
#define IDC_STAT_UNIT                   1027
#define IDC_STAT_MSG_DETAILS            1027
#define IDC_EDIT_GLOBAL_NAME            1027
#define IDC_RADIO_ACTION_NONE           1027
#define IDC_STAT_MAX                    1028
#define IDC_CHKB_WANT_STRUCTURE         1028
#define IDC_BUTTON_REMOVEALL            1028
#define IDC_STAT_MIN                    1029
#define IDC_STAT_MSG_NAME               1029
#define IDC_COMB_FN_RETURN_TYPE         1029
#define IDC_STAT_TYPE                   1030
#define IDC_EDIT_FN_PROTO               1030
#define IDC_EDIT_CSV_FILE_NAME          1030
#define IDC_STAT_OFFSET                 1031
#define IDC_STAT_MSG_CODE               1031
#define IDC_STAT_RETURN_TYPE            1031
#define IDC_EDIT_INTERPRETED_MSG        1031
#define IDC_EDIT_HTML_FILE_NAME         1031
#define IDC_BTN_CONFIGURE               1031
#define IDC_EDIT_OFFSET                 1032
#define IDC_STATIC_MSGLEN               1032
#define IDC_STAT_FN_PROTO               1032
#define IDC_EDIT_IMAGE_FILE_NAME        1032
#define IDC_STAT_NOOFSGS                1033
#define ID_CTBN_OK                      1033
#define IDC_BTN_BROWSE_CSV              1033
#define IDC_EDIT_NOOFSGS                1034
#define IDC_STAT_SGDET                  1034
#define ID_CBTN_CANCEL                  1034
#define IDC_BTN_BROWSE_HTML             1034
#define IDC_EDIT_MSGCODE                1035
#define IDC_STAT_SEL_FNGRP              1035
#define IDC_BTN_BROWSE_BMP              1035
#define IDC_STAT_MSGGRP                 1036
#define IDC_EDIT_CANID_STRING           1036
#define IDC_BTN_SAVE_CSV                1036
#define IDC_EDIT_CANID_VAL              1037
#define IDC_BTN_SAVE_HTML               1037
#define IDC_PBTN_COLOUR                 1038
#define IDC_CHECK_PRINT_REPORT          1038
#define IDC_CBTN_SEL_COLOUR             1039
#define IDC_BTN_EXPORT                  1039
#define IDC_BTN_SAVE_HTML2              1039
#define IDC_STAT_VALUE_DESC             1040
#define IDC_LSTB_CANID_LIST             1040
#define IDC_BTN_VISIBLE                 1040
#define IDC_EDIT_TIME_DELAY             1041
#define IDC_STAT_VALUE                  1041
#define IDC_CBTN_CANID_ADD              1041
#define IDC_EDIT_RANGE_FROM             1041
#define IDC_CBTN_OK                     1042
#define IDC_CBTN_CANID_REMOVE           1042
#define IDC_EDIT_RANGE_TO               1042
#define IDC_CBTN_CANCEL                 1043
#define IDC_CBTN_CANID_EDIT             1043
#define IDC_BTN_SET                     1043
#define IDC_STATDESCGP                  1044
#define IDC_EDIT_TIMER_FUNCTION_NAME    1044
#define IDC_CBTN_APPLY                  1044
#define IDC_BTN_AUTO_FIT                1044
#define IDC_EDIT_TIMER_VALUE            1045
#define IDC_BTN_COPY                    1045
#define IDC_STAT_TIMER_FUNCTION         1046
#define IDC_BTN_GRID                    1046
#define IDC_STAT_MILI_SECOND            1047
#define IDC_STAT_SGGROUP                1048
#define IDC_STAT_TIMER_VALUE            1048
#define IDC_BTN_AUTO_FIT2               1048
#define IDC_BTN_FIT_ALL                 1048
#define IDC_EDIT_FILENAME               1049
#define IDC_STAT_SGIDVALGRP             1050
#define IDC_STAT_INCLUDE_HEADER         1050
#define IDC_BUTTON_SELECTALL            1050
#define IDC_CBTN_BROWSE                 1051
#define IDC_CBTN_REPLAY_BROWSE          1052
#define IDC_STAT_GRP                    1053
#define IDC_APPLY_BUTTON                1054
#define IDC_STAT                        1055
#define IDC_LIST_SIGNAL_WATCH           1056
#define IDC_STAT_8                      1057
#define IDC_COMBO_MSGTYPE               1058
#define IDC_STAT_LOG                    1059
#define IDC_ButtonOK                    1060
#define IDC_STAT_REPLAY                 1060
#define IDC_STAT_LOG_FILE               1061
#define IDC_EDIT_LOGFILENAME            1062
#define IDC_EDIT_LOGFILEPATH            1062
#define IDC_STAT_REPLAY_FILE            1063
#define IDC_EDIT_REPLAY_FILE            1064
#define IDC_STAT_7                      1065
#define IDC_STAT_REPLAY_MODE            1065
#define IDC_STAT_6                      1066
#define IDC_RBTN_SINGLE                 1066
#define IDC_STAT_5                      1067
#define IDC_RBTN_CYCLIC                 1067
#define IDC_LSTB_MSGID_LIST             1068
#define IDC_LSTC_SIGNALS                1068
#define IDC_LSTB_MSGID_DISPLAY_LIST     1068
#define IDC_LSTB_SIGNAL                 1068
#define IDC_LSTB_FUNCTIONS              1068
#define IDC_LSTB_MSGID_FILTER_LIST      1069
#define IDC_LSTC_SGIDVAL                1069
#define IDC_LSTC_MSGS                   1069
#define IDC_CBTN_MSGID_FILTER_ADD       1070
#define IDC_STATIC_FRAMEFORMAT          1070
#define IDC_LSTC_SIGNAL_WATCH           1070
#define IDC_CBTN_MSGLIST_SWAP           1071
#define IDC_STATIC_DATA_FORMAT          1071
#define IDC_LSTC_SIGNAL                 1071
#define IDC_CBTN_MSGID_FILTER_REMOVE    1072
#define IDC_STATIC_FF                   1072
#define IDC_STAT_4                      1073
#define IDC_STATIC_DF                   1073
#define IDC_STAT_3                      1074
#define IDC_STAT_2                      1075
#define IDC_BUTTON_NEWSIGNAL            1075
#define IDC_STAT_1                      1076
#define IDC_BUTTON_EDITSIGNAL           1076
#define IDC_STAT_GRPTIMEDELAY           1076
#define IDC_CHKB_TIMER1                 1077
#define IDC_STAT_KEY                    1077
#define IDC_BUTTON_DELETESIGNAL         1077
#define IDC_CHK_DEFAULT_TIME            1077
#define IDC_CHKB_TIMER2                 1078
#define IDC_STAT_DELAY_CYLCES           1078
#define IDC_CHKB_TIMER3                 1079
#define IDC_EDIT_TIME_DELAY_BETN_CYCLES 1079
#define IDC_RBTN_APPEND                 1079
#define IDC_CHKB_TIMER4                 1080
#define IDC_STAT_MSEC                   1080
#define IDC_RBTN_OVERWRITE              1080
#define IDC_CHKB_TIMER5                 1081
#define IDC_EDIT_TIME_DELAY_BETN_MSGS   1081
#define IDC_RBTN_DECIMAL                1081
#define IDC_CHKB_TIMER6                 1082
#define IDC_STAT_DELAY_BETN_MSG         1082
#define IDC_RBTN_HEX                    1082
#define IDC_CHKB_TIMER7                 1083
#define IDC_STAT_MSEC1                  1083
#define IDC_CHKB_TIMER8                 1084
#define IDC_STAT_9                      1084
#define IDC_STAT_PIC_LOG                1084
#define IDC_CHKB_TIMER9                 1085
#define IDC_STAT_10                     1085
#define IDC_STAT_PIC_REPLAY             1085
#define IDC_CHKB_TIMER10                1086
#define IDC_STAT_11                     1086
#define IDC_CHKB_TYPE_TIMER1            1087
#define IDC_STAT_12                     1087
#define IDC_STAT_MSGLIST                1088
#define IDC_CHKB_TYPE_TIMER2            1088
#define IDC_STAT_13                     1088
#define IDC_STAT_FILTERLIST             1089
#define IDC_CHKB_TYPE_TIMER3            1089
#define IDC_STAT_14                     1089
#define IDC_CBTN_ADD_DESC               1089
#define IDC_CHKB_RECODR_UKNOWN_MSG      1090
#define IDC_EDIT_MTX1                   1090
#define IDC_EDIT_SGVALUE                1090
#define IDC_CHKB_FILTER_UKDEFINED_MSG   1090
#define IDC_CHKB_TYPE_TIMER4            1090
#define IDC_CBTN_EDIT_DESC              1090
#define IDC_EDIT_MSGRANGE_FROM          1091
#define IDC_CHKB_TYPE_TIMER5            1091
#define IDC_STAT_15                     1091
#define IDC_CBTN_DEL_DESC               1091
#define IDC_EDIT_MSGRANGE_TO            1092
#define IDC_CHKB_TYPE_TIMER6            1092
#define IDC_STAT_16                     1092
#define IDC_TREE1                       1092
#define IDC_CHKB_ENABLE_LOG_ONCONNECT   1092
#define IDC_CHKB_TYPE_TIMER7            1093
#define IDC_LSTC_DB_MSGS                1093
#define IDC_CHKB_FILTER_TXMSG           1094
#define IDC_CHKB_TYPE_TIMER8            1094
#define IDC_LSTC_SND_MSGS               1094
#define IDC_STAT_TIME_DELAY             1095
#define IDC_CHKB_TYPE_TIMER9            1095
#define IDC_CBTN_MOVE_RIGHT             1095
#define IDC_EDIT_STARTMSGID             1095
#define IDC_STAT_MILISECOND             1096
#define IDC_CHKB_TYPE_TIMER10           1096
#define IDC_CBTN_MOVE_LEFT              1096
#define IDC_EDIT_STOPMSGID              1096
#define IDC_CBTN_CFG                    1097
#define IDC_CBTN_CFG_DB_MSG             1097
#define IDC_LSTC_MSG_DETAILS            1099
#define IDC_CHANNEL                     1099
#define IDC_CBTN_MORE                   1100
#define IDC_CBTN_SEND                   1101
#define IDC_COMB_TIMEMODE               1101
#define IDC_CBTN_CLEAR_LIST             1102
#define IDC_COMB_CHANNEL                1102
#define IDC_LOGBLOCK_LST                1112
#define IDC_LOGFILE_GROUP               1113
#define IDC_NUMERICFORMAT_GROUP         1115
#define IDC_CHKB_STARTTRIGGER           1116
#define IDC_STAT_LINE2                  1117
#define IDC_CHKB_STOPTRIGGER            1117
#define IDC_STAT_LINE1                  1118
#define IDC_FILEMODE_GROUP              1118
#define IDC_STAT_LINE3                  1119
#define IDC_LOGTRIGGER_GROUP            1119
#define IDC_STAT_RECT                   1120
#define IDC_STAT_LINE4                  1120
#define IDC_CBTN_NEW_CONTROLS           1121
#define IDC_LOG_FILTER                  1121
#define IDC_CBTN_UPDATE_MSG             1122
#define IDC_STAT_HEADER                 1122
#define IDC_CBTN_ADD_MSG                1122
#define IDC_CBTN_LOGFILEPATH            1122
#define IDC_STAT_HEADER2                1124
#define IDC_EDIT_DLC                    1125
#define IDC_EDIT_DB1                    1126
#define IDC_EDIT_DB2                    1127
#define IDC_EDIT_DB3                    1128
#define IDC_EDIT_DB4                    1129
#define IDC_EDIT_DB5                    1130
#define IDC_EDIT_DB6                    1131
#define IDC_EDIT_DB7                    1132
#define IDC_EDIT_DB8                    1133
#define IDC_EDIT_TRG_TIME_VAL           1134
#define IDC_STAT_MSG_HEADER             1137
#define IDC_EDIT_TRG_KEY_VAL            1137
#define IDC_STAT_MSGS                   1138
#define IDC_STAT_DELAY                  1141
#define IDC_CHK_MONOSHOT                1142
#define IDC_STAT_DALC                   1143
#define IDC_STAT_DATA_BYTES             1144
#define IDC_STAT_ICON                   1145
#define IDC_STAT_BMP                    1145
#define IDC_RBTN_PASSFILTER             1147
#define IDC_STAT_MSG_BYTES              1147
#define IDC_RBTN_STOPFILTER             1148
#define IDC_EDIT_PROP_BAUDRATE          1148
#define IDC_EDIT_PROP_LOGFILE           1149
#define IDC_STAT_GRP_MODE               1150
#define IDC_EDIT_PROP_REPLAYFILE        1150
#define IDC_STAT_UNDEFMSG               1151
#define IDC_EDIT_PROP_DATABASEFILE      1151
#define IDC_EDIT_MSG_ID                 1152
#define IDC_STAT_PROP_BAUDRATE          1152
#define IDC_STAT_GRP_TRIGGER            1153
#define IDC_STAT_PROP_LOGFILE           1153
#define IDC_STATIC_VERSION              1153
#define IDC_STAT_MSGID                  1154
#define IDC_STAT_PROP_DATABASEFILE      1154
#define IDC_EDIT_MSGID                  1155
#define IDC_STAT_PROP_REPLAYFILE        1155
#define IDC_CHKB_ERROR_ACTIVE_HANDLER   1155
#define IDC_EDIT_MSG_HANDLER_ID         1155
#define IDC_EDIT_MSGNAME                1156
#define IDC_EDIT_PROP_DLLFILE           1156
#define IDC_CHKB_ERROR_PASSIVE_HANDLER  1156
#define IDC_CBTN_BROWSEMSG              1157
#define IDC_STAT_PROP_DLLFILE           1157
#define IDC_CHKB_WARNING_LIMIT_HANDLER  1157
#define IDC_STAT_OPTIONS                1158
#define IDC_STATIC_VERSION_PROP         1158
#define IDC_CHKB_BUS_OFF_HANDLER        1158
#define IDC_CHKB_ERROR_FRAME_HANDLER    1159
#define IDC_STAT_TAG_KEY_INTERVAL       1159
#define IDC_STAT_DELAY2                 1160
#define IDC_EDIT_MSG_HANDLER_ID_FROM    1160
#define IDC_STAT_UNIT_MS                1160
#define IDC_EDIT_MSG_HANDLER_ID_TO      1161
#define IDC_STAT_TAG_KEY_INTERVAL2      1161
#define IDC_STATIC_BULB                 1163
#define IDC_STAT_MSGBYTE                1164
#define IDC_STAT_MSGBYTES               1164
#define IDC_CHKB_DLL_LOAD_HANDLER       1164
#define IDC_CHKB_DLL_UNLOAD_HANDLER     1165
#define IDC_CBTN__MSG_OK                1167
#define IDC_CBTN__MSG_CANCEL            1168
#define IDC_LSTB_MSG_HANDLER_LIST       1169
#define IDC_RBTN_MSG_NAME               1170
#define IDC_RBTN_MSG_ID                 1171
#define IDC_RBTN_MSG_RANGE              1172
#define IDC_RBTN_MSG_ALL                1173
#define IDC_CBTN_MSG_HANDLDER_APPLY     1174
#define IDC_EDIT_WARNING_LIMIT          1175
#define IDC_CBTN__ERROR_OK              1176
#define IDC_CBTN__ERROR_CANCEL          1177
#define IDC_CBTN__DLL_OK                1178
#define IDC_CBTN__DLL_CANCEL            1179
#define IDC_STAT_DRIVER_VERSION         1180
#define IDC_EDIT1                       1181
#define IDC_EDIT_ACCEPTANCE_CODE2       1181
#define IDC_EDIT_APPEND_SIZE            1181
#define IDC_EDIT_BUFFER_SIZE            1181
#define IDC_EDIT_TO                     1181
#define IDC_EDIT_BROADCAST              1181
#define IDC_EDIT_OVERWRITE_SIZE         1182
#define IDC_EDIT_X_GRIDS                1182
#define IDC_EDIT_DISPLAY_UPDATE         1183
#define IDC_EDIT_UTILS_FN               1184
#define IDC_EDIT_Y_GRIDS                1184
#define IDC_EDIT_MSG_PER_SECOND         1185
#define IDC_EDIT_TX_STD                 1186
#define IDC_EDIT_TX_TOTAL               1187
#define IDC_EDIT_TX_EXTD                1188
#define IDC_EDIT_RX_TOTAL               1190
#define IDC_EDIT_RX_STD                 1191
#define IDC_EDIT_RX_EXTD                1192
#define IDC_EDIT_ERROR_TOTAL            1194
#define IDC_EDIT_ERROR_RX               1195
#define IDC_EDIT_ERROR_TX               1196
#define IDC_EDIT_MSG_TOTAL              1197
#define IDC_LSTB_NOTIFIC_WND            1198
#define IDC_EDIT_TX_RTR_STD             1198
#define IDC_EDIT_TX_RTR_EXTD            1199
#define IDC_CBTN_ACCEPTANCE             1199
#define IDC_EDIT_RX_RTR_STD             1200
#define IDC_CBTN_ACCETANCE_OK           1200
#define IDC_CBTN_BLINK                  1200
#define IDC_EDIT_RX_RTR_EXTD            1201
#define IDC_EDIT_ACCEPTANCE_MASK2       1201
#define IDC_EDIT_ACCEPTANCE_CODE3       1202
#define IDC_EDIT_BUS_LOAD               1202
#define IDC_EDIT_ACCEPTANCE_MASK3       1203
#define IDC_EDIT_PEAK_BUS_LOAD          1203
#define IDC_EDIT_ACCEPTANCE_MASK1       1204
#define IDC_EDIT_ACCEPTANCE_MASK4       1205
#define IDC_EDIT_ACCEPTANCE_CODE1       1206
#define IDC_EDIT_ACCEPTANCE_CODE4       1207
#define IDC_RBTN_SINGLE_FILTER_MODE     1208
#define IDC_RBTN_DUAL_FILTER_MODE       1209
#define IDC_STAT_FILTER_MODE            1210
#define IDC_STAT_ACCEPTANCE_FILTER_CODE 1211
#define IDC_STAT_ACCEPTANCE_FILTER_MASK 1212
#define IDC_RBTN_MSGTYPE_EXTD           1213
#define IDC_RBTN_MSGTYPE_STD            1215
#define IDC_CHKB_MSGTYPE_RTR            1216
#define IDC_GRPB_TX_MSG_LIST            1217
#define IDC_STAT_MSG_CODE_HEX           1218
#define IDC_MATRIX_RECT                 1219
#define IDC_CHKB_HEX                    1219
#define IDC_STAT_USRPROMPT              1220
#define IDC_RBTN_SYSTEM_MODE            1220
#define IDC_RBTN_ABSOLUTE_MODE          1221
#define IDC_COMB_MSG_ID_NAME            1221
#define IDC_STAT_MSGNAME                1222
#define IDC_STAT_TRIGGER_TYPE           1222
#define IDC_CONTROL_RECT                1223
#define IDC_RBTN_RELATIVE_MODE          1223
#define IDC_RBTN_ON_KEY                 1223
#define IDC_STAT_MSG_ID                 1224
#define IDC_CHEK_OVER_WRITE_MODE        1224
#define IDC_RBTN_ON_TIME                1224
#define IDC_STAT_DLC                    1225
#define IDC_COMB_REPLAY_TYPE            1225
#define IDC_LSTC_MSG_BLOCKS_NAME        1225
#define IDC_STAT_DATABYTES              1226
#define IDC_LIST1                       1226
#define IDC_CBTN_ADD_MSG_BLOCK_NAME     1226
#define IDC_CBTN_ADD_MSG_BLOCK          1226
#define IDC_LIST_STAT                   1226
#define IDC_LSTC_SELECTED_HW_LIST       1226
#define IDC_LIST_LOG_FILES              1226
#define IDC_LIST_REPALY_FILES           1226
#define IDC_LST_DISPLAY_FILTER_LIST     1226
#define IDC_LSTC_HANDLER_DETAILS        1226
#define IDC_BTN_OK                      1227
#define IDC_CBTN_DELETE_MSG_BLOCK_NAME  1227
#define IDC_CBTN_DELETE_MSG_BLOCK       1227
#define IDC_CAPTION                     1227
#define IDC_EDIT_MSG_BLOCK_NAME         1228
#define IDC_CAPTION2                    1228
#define IDC_BTN_ADD                     1228
#define IDC_CBTN_SEND_MSG               1229
#define IDC_LIST_SIGNAL                 1229
#define IDC_BTN_ADD_ALL                 1229
#define IDC_CBTN_DELETE_SEL_MSG         1230
#define IDC_BTN_DEL                     1230
#define IDC_CBTN_DELETE_ALL_MSG         1231
#define IDC_BUTTON_ADD                  1231
#define IDC_COMB_MSGNAME                1231
#define IDC_BUTTON_EDIT                 1232
#define IDC_BTN_DEL_ALL                 1232
#define IDC_LSTC_SIG_DETAILS            1232
#define IDC_BUTTON_REMOVE               1233
#define IDC_STAT_STATUS                 1233
#define IDC_LIST_MESSAGE                1235
#define IDC_CHKB_ON_TIME_TRIGGER        1236
#define IDC_CHKB_ON_KEY_TRIGGER         1237
#define IDC_CBTN_SET_DEFAULT            1241
#define IDC_STAT_COPYRIGHT              1242
#define IDC_GRAPH_CTRL                  1244
#define IDC_WEB_BROWSER                 1245
#define IDC_TREE_PROPERTIES             1246
#define IDC_LIST_CHANNELS               1246
#define IDC_STAT_161                    1247
#define IDC_STAT_151                    1248
#define IDC_STAT_MATRIX_RECT            1249
#define IDC_BTN_DELETE_FILTER           1250
#define IDC_BTN_DELETE_ALL_FILTER       1251
#define IDC_RADIO_ID                    1253
#define IDC_RADIO_RANGE                 1254
#define IDC_STATIC_TO_STRING            1255
#define ID_OK                           1256
#define IDC_BTN_ADD_FILTER              1257
#define IDC_LSTC_FILTER_LIST            1258
#define IDC_RADIO_FILE_MODE             1259
#define IDC_RADIO_FILE_MODE1            1260
#define IDC_BTN_FILE_BROWSE             1261
#define IDC_BTN_ADD_FILE                1262
#define IDC_STATIC_STATUS               1263
#define IDC_CHECK4                      1264
#define IDC_CHK_LOG_TRIGGER_START       1264
#define IDC_CHECK_T1                    1264
#define IDC_CHECK5                      1265
#define IDC_CHK_LOG_TRIGGER_STOP        1265
#define IDC_CHECK_T2                    1265
#define IDC_STAT_NODE_DETAILS           1266
#define IDC_EDIT_FILE_NAME              1267
#define IDC_STAT_NODE_NAME              1268
#define IDC_STAT_FILE_NAME              1269
#define IDC_STAT_FILEGRP                1270
#define IDC_STAT_HANGROUP               1271
#define IDC_LSTC_HANVAL                 1272
#define IDC_STAT_HANDESC                1273
#define IDC_STAT_HANDLER_VAL            1274
#define IDC_STAT_NODE_LIST              1275
#define IDC_COMB_NODENAME               1276
#define IDC_EDIT_ANODE_NAME             1278
#define IDC_STAT_SELCHANNEL             1284
#define IDC_CBTN_DISSOCIATE             1285
#define IDC_LSTB_DISSOCIATE_DBNAMES     1286
#define IDC_GROUPBOX_TRIGGER            1287
#define IDC_EDIT_DEFAULT_SIGNAL_VALUE   1288
#define IDC_BTN_APPLY                   1300
#define SD_STA_IMAGE_2                  1300
#define IDC_CBTN_ADDLOG                 1303
#define IDC_CBTN_DELETELOG              1304
#define IDC_RADIO_INTEL                 1306
#define IDC_RADIO_MOTOROLA              1307
#define IDC_EDIT_01                     1310
#define IDC_SELECT_DRIVER               1311
#define IDC_SELECT_DRIVER_END           1327
#define IDC_COMBO_DISPLAY               1328
#define IDC_STATIC_NOTICE               1328
#define IDC_COMBO_LINE_DISPLAY          1329
#define IDC_STATIC_PICTURE              1329
#define IDC_STATIC_01                   1330
#define IDC_EDIT_ECU_NAME               1330
#define IDC_STATIC_2                    1331
#define IDC_STATIC_02                   1331
#define IDC_STATIC_ECU_NAME             1331
#define IDC_STATIC_NODE                 1332
#define IDC_EDIT_FROM                   1333
#define IDC_STATUSBAR                   1334
#define IDC_RADIO_NM                    1335
#define IDC_EDIT_CA                     1336
#define IDC_STATIC_CA                   1337
#define IDC_EDIT_PGN                    1338
#define IDC_EDIT4                       1339
#define IDC_EDIT_MILI_SEC               1339
#define IDC_EDIT_T1                     1339
#define IDC_CHECK_T3                    1340
#define IDC_CHECK_T4                    1341
#define IDC_EDIT_T2                     1342
#define IDC_EDIT_T3                     1343
#define IDC_EDIT7                       1344
#define IDC_EDIT_T4                     1344
#define IDC_STATIC_DESCRIPTION          1345
#define IDC_COMBO2                      1346
#define IDC_COMBO_PGN                   1346
#define IDC_STATIC_PRIORITY             1347
#define IDC_EDIT5                       1348
#define IDC_EDIT_PRIORITY               1348
#define IDC_STATIC_CHANNEL              1349
#define DLG_TEMPLATE_LOCKING_KEY        13030
#define IDR_TOOL_BUTTON_SIGNAL_WATCH    32784
#define IDR_TOOL_BUTTON_SKIP            32785
#define IDR_TOOL_BUTTON_GO              32787
#define IDR_TOOL_BUTTON_MSG_DISP        32788
#define IDR_TOOL_BUTTON_LOG             32790
#define IDR_TOOL_BUTTON_RST_CRTL        32791
#define IDR_TOOL_BUTTON_MSG_INT         32792
#define IDM_LOG_SELECTFILE              32799
#define IDM_REPLAY_OFF                  32800
#define IDM_REPLAY_SELECTFILE           32801
#define IDM_REPLAY_GO                   32802
#define IDM_REPLAY_STEP                 32803
#define IDM_REPLAY_SKIP                 32804
#define IDM_REPLAY_STOP                 32805
#define IDM_LOG_ON_OFF                  32806
#define IDM_CONFIGURE_MESSAGE           32809
#define IDM_ADD_MSG_BLOCK               32810
#define IDM_CONFIGURE_BAUDRATE          32811
#define IDM_CONFIGURE_DATABASE          32813
#define IDM_CONFIGURE_DATABASE_NEW      32815
#define IDM_DELETE_SEL_MSG_BLOCK        32816
#define IDM_CONFIGURE_DATABASE_OPENACTIVE 32817
#define IDM_SIGNALWATCH_ADDSIGNAL       32818
#define IDM_SIGNALWATCH_CLOSE           32819
#define IDM_FILTER_MESSAGE_SELECTMESSAGES 32821
#define IDM_FILTER_MESSAGE_OFF          32823
#define IDM_FILTER_LOGFILTEROFF         32824
#define IDM_FILTER_MESSAGEFILTEROFF     32826
#define IDM_BUILD_COMPILEANDLINK        32828
#define IDM_DISPLAY_MESSAGEWINDOW_SCROLL 32834
#define IDM_DISPLAY_MESSAGE_HIDE        32835
#define IDM_DISPLAY_MESSAGE_DISPLAYRELATIVETIME 32836
#define IDM_DISPLAY_SIGNALWATCHWINDOW   32837
#define IDM_DISPLAY_MESSAGEWATCHWINDOW_INTERPRET 32838
#define ID_HELP_ABOUTCANDRIVER          32839
#define IDR_TOOL_HEXDEC                 32839
#define IDR_TOOL_BUTTON_TIMER_HDLR      32840
#define IDR_TOOL_BUTTON_STEP            32841
#define IDR_TOOL_BUTTON_STOP            32842
#define IDR_TOOL_SCROLL                 32844
#define IDR_TOOL_TIME                   32845
#define ID_CONFIGURE_DATABASE_CLOSE     32846
#define ID_EXECUTE_MESSAGEHANDLERS      32847
#define IDM_EXECUTE_MESSAGEHANDLERS     32848
#define IDM_CONFIGURE_DATABASE_CLOSE    32849
#define IDM_EXECUTE_TIMERHANDLER        32850
#define IDM_REPLAY_MODE_SINGLE          32852
#define IDM_REPLAY_MODE_CYCLIC          32853
#define IDM_DISPLAY_SIGNAL_ADD          32854
#define IDM_DLL_UNLOAD                  32855
#define IDM_DLL_LOADDLL                 32856
#define IDM_DLL_BUILDLOAD               32857
#define IDM_DLL_BUILD                   32858
#define IDM_DLL_STOPBUILD               32859
#define IDM_FILE_IMPORT_DATABASE        32860
#define IDM_NEW_SIGNAL                  32861
#define IDM_DELETE_SIGNAL               32863
#define IDM_CONFIGURE_DATABASE_SAVE     32864
#define IDM_CONFIGURE_DATABASE_SAVEAS   32865
#define IDM_NEW_MSG                     32866
#define IDM_DELETE_MSG                  32867
#define IDM_APP_ABOUT                   32869
#define IDM_FILE_RESTART_CONTROLLER     32871
#define IDR_TOOL_SENDMSG                32873
#define IDM_EXECUTE_MESSAGEHANDLERS_BUTTON 32875
#define IDM_FILTER_MESSAGEFILTEROFF_BUTTON 32876
#define IDR_DESCVAL_DELETE              32877
#define IDM_FILTER_LOGFILTEROFF_BUTTON  32877
#define IDM_DISPLAY_MESSAGEWINDOW_OVERWRITE 32878
#define IDM_CLEAR_MSG_WINDOW            32879
#define IDM_SG_WATCH_DELETE             32880
#define IDM_SG_WATCH_CLEAR              32881
#define IDM_FILE_DATABASE               32882
#define IDM_FILE_EDITOR                 32883
#define IDM_CFGN_LOGREPLAY              32884
#define IDM_EDIT_MSG                    32885
#define ID_SEND_MULTI_MSGS              32887
#define IDM_NEW_UDEFNED_MSG             32888
#define IDM_DELETE                      32889
#define IDR_TOOL_STOPSENDMSG            32890
#define IDM_CFGN_SEND_MSGS              32891
#define IDM_DELETE_SEL_MSG              32892
#define IDM_MSGDISPWND_MSGREP           32893
#define IDM_MSGDISPWND_DATE             32894
#define IDM_SHOW_DATE                   32896
#define IDM_SEND_SEL_MSG                32897
#define IDM_DELETE_ALL_SEL_MSG          32898
#define IDM_SEND_ALL_SEL_MSG            32898
#define IDM_BUTTON_CONNECT              32899
#define IDM_EXECUTE_KEYHANDLERS         32900
#define IDM_CONFIG_NEW                  32902
#define IDM_CONFIG_LOAD                 32903
#define IDM_SAVE_CONFIG                 32904
#define IDM_SAVEAS_CONFIG               32905
#define IDM_EXECUTE_ALL_HANDLERS        32909
#define IDM_EXECUTE_ERROR_HANDLERS      32910
#define IDM_EXECUTE_DLL_HANDLERS        32911
#define IDR_DESCVAL_EDIT                32912
#define IDM_DESCVAL_ADD                 32913
#define IDM_CONFIGURE_MODE              32913
#define IDS_MESSAGE_ID                  32915
#define IDM_EDIT_SIGNAL                 32916
#define IDM_NETWORK_STATISTICS_WND      32918
#define IDM_CONFIGURE_SELF_TEST         32919
#define IDM_CONFIGURE_PASSIVE           32920
#define IDM_CONFIGURE_ACTIVE            32921
#define IDM_TRACE_WND                   32922
#define IDM_CHECK_HW_INTERFACE          32925
#define IDM_PARALLEL_PORT_EPP           32926
#define IDM_PARALLEL_PORT_NONEPP        32927
#define IDM_FUNCTIONS_RESET_HARDWARE    32930
#define IDM_REC_CFG_FILE1               32932
#define IDM_REC_CFG_FILE2               32933
#define IDM_REC_CFG_FILE3               32934
#define IDM_REC_CFG_FILE4               32935
#define IDM_REC_CFG_FILE5               32936
#define IDM_MESSAGE_WINDOW              32937
#define IDM_DISPLAY_MESSAGE_DISPLAY_SYSTEM_TIME 32938
#define ID_DISPLAY_MESSAGEWINDOW_TIMEMODE_RELATIVETIME 32939
#define ID_DISPLAY_MESSAGEWINDOW_TIMEMODE_ABSOLUTETIME 32940
#define IDM_DISPLAY_MESSAGE_DISPLAY_ABSOLUTETIME 32941
#define IDM_DISPLAY_MESSAGE_DISPLAY_RELATIVETIME 32942
#define IDM_DELETE_ALL_MSG              32944
#define IDM_MESSAGE_SEND                32946
#define IDM_SIGNALDLG_ADDALL            32946
#define IDM_SIGNALDLG_DELETE            32947
#define IDM_SIGNALDLG_DELETEALL         32948
#define IDM_SIGNALDLG_SIGNALDETAILS     32949
#define IDM_SIGNALDLG_ADD               32950
#define IDM_MESSAGE_EXPAND              32951
#define IDM_DISPLAY_MESSAGEWATCHWINDOW_SCROLL 32952
#define IDM_GRAPH_WND                   32953
#define IDM_CFGN_REPLAY                 32955
#define IDM_CFGN_LOG                    32956
#define ID_OPTION_EXPORT_LOGFILE        32958
#define IDM_OPRTN_CLEAR                 32968
#define IDM_OPRTN_DELETE                32971
#define IDM_DATABASE_DISSOCIATE_DB      33001
#define ID_TXMESSAGE_WTRWTW             33003
#define ID_FILE_EXTERNALTOOLS           33004
#define ID_EXTERNALTOOLS_CAPLTOCCONVERTER 33005
#define ID_EXTERNALTOOLS_DBCTODBFCONVERTER 33006
#define IDM_SAVE_IMPORT                 33010
#define ID_EXTERNALTOOLS_DBFTODBCCONVERTER 33012
#define ID_TRACE_WINDOW                 33015
#define ID_MESSAGE_WINDOW               33016
#define ID_HELLO_HI                     33017
#define ID_CONTROLLERMODE_SIMULATE      33018
#define IDM_DLL_BUILD_ALL               33019
#define IDM_DLL_BUILDLOAD_ALL           33020
#define IDM_DLL_LOADALLDLL              33021
#define IDM_DLL_UNLOAD_ALL              33022
#define IDM_CONFIGURE_SIMULATEDSYSTEMS  33023
#define ID_DISPLAY_MESSAGEWINDOW        33039
#define ID_BUILD_LOADCANMONITORDLL      33040
#define ID_NOTIFICWND_SELECTALL         33041
#define IDM_MSGWND_RESET_COLUMNS        33042
#define ID_NOTIFICWND_COPYTOCLIPBOARD   33042
#define ID_DISPLAY_EDIT                 33043
#define ID_DISPLAY_FILTERS              33044
#define ID_DISPLAY_FUNC_EDITOR          33045
#define ID_DISPLAY_MAIN                 33046
#define ID_DISPLAY_MSG_WND              33047
#define ID_DISPLAY_MSG_REPLAY           33048
#define ID_DISPLAY_NODE_SIMULATION      33049
#define ID_CONFIGURE_WAVEFORM_MESSAGES  33051
#define IDR_START_SIGNAL_TRANSMISSION   33052
#define ID_ACTIVEBUS_CAN                33053
#define ID_TOOLBAR_SIGNALGENERATION     33054
#define ID_CONFIGURE_SIGNALGRAPHWINDOW  33055
#define ID_SIGNALGRAPHWINDOW_FLEXRAY    33060
#define ID_SIGNALGRAPHWINDOW_CAN        33061
#define ID_TOOLBAR_CONFIGURE            33065
#define ID_BUTTON33067                  33067
#define ID_BUTTON33069                  33069
#define IDM_CONFIGURE                   33072
#define ID_DISPLAY_CONFIGURE            33073
#define ID_DISPLAY_SIGNALGRAPHWINDOW    33075
#define ID_SIGNALGRAPHWINDOW_MCNET      33076
#define ID_CONFIGURE_TIMEOUTS           33077
#define ID_CONFIGURE_DATABASE           33078
#define ID_DATABASE_NEW                 33079
#define ID_DATABASE_OPEN                33080
#define ID_FUNCTION_DATABASE            33081
#define ID_DATABASE_ASSOCIATE           33082
#define ID_DATABASE_DISSOCIATE          33083
#define ID_DATABASE_CLOSE               33084
#define ID_CONFIGURE_SIMULATEDSYSTEMS   33085
#define ID_FUNCTION_USERPROGRAM         33086
#define ID_USERPROGRAM_LOADALL          33087
#define ID_USERPROGRAM_UNLOADALL        33088
#define ID_USERPROGRAM_BUILDANDLOADALL  33089
#define ID_USERPROGRAM_BUILDALL         33090
#define ID_USERPROGRAM_EXECUTE          33091
#define ID_EXECUTE_ALLMESSAGEHANDLERS   33092
#define ID_EXECUTE_ALLKEYHANDLERS       33093
#define ID_EXECUTE_ALLTIMERHANDLERS     33094
#define ID_EXECUTE_ALLERRORHANDLERS     33095
#define ID_EXECUTE_ALLHANDLERS          33096
#define ID_CONFIGURE_SIGNALWATCH        33097
#define ID_SIGNALWATCH_ADD              33098
#define ID_SIGNALWATCH_SHOWWINDOW       33099
#define ID_FUNCTION_SIGNALWATCH         33100
#define ID_Menu                         33101
#define ID_FUNCTION_EXPORTLOG           33102
#define ID_SHOWMESSAGEWINDOW_CAN        33105
#define ID_NODESIMULATION_EXECUTE       33107
#define ID_FILE_UTILITIES               33109
#define ID_BUTTON33112                  33112
#define ID_BUTTON33113                  33113
#define ID_BUTTON33114                  33114
#define ID_BUTTON33115                  33115
#define ID_TB_CANDATABASE               33117
#define ID_FUNCTIONS_TESTAUTOMATION     33118
#define ID_TESTAUTOMATION_EDITOR        33119
#define ID_TESTAUTOMATION_EXECUTOR      33120
#define ID_CONFIGURE_CHANNELSELECTION   33121
#define IDS_PROPT_FOR_EMPTY_FILENAME    61446
#define IDS_INVALID_DB_PROMPT           61447
#define IDC_COMB_TOOLBAR                61448
#define ID_ACTIVE_DATABASE_NAME         61448
#define IDM_CONTEXT_INSERTFUNCTION      61449
#define IDS_MESSAGE_NAME                61449
#define IDM_CONTEXT_INSERTMESSAGE       61450
#define IDM_CONTEXT_INSERTSIGNAL        61451
#define IDS_VERSION                     61451
#define IDS_HEADER                      61452
#define IDS_FOOTER                      61453
#define IDS_CONNECT                     61454
#define IDS_DISCONNECT                  61455
#define IDM_FILE_CONNECT                62454
#define IDM_FILE_PROPETIES              62455
#define IDS_ERROR_MODE                  62456
#define IDS_ERROR_COUNTER               62457
#define IDS_PPAGE_TITLE_DBMSG           62458
#define IDS_PPAGE_TITLE_NDBMSG          62459
#define IDS_SHOW                        62460
#define IDS_HIDE                        62461
#define IDS_PPAGE_TITLE_BUFFER          62462
#define IDS_CHANNELS                    62463
#define IDS_PPAGE_TITLE_MSG_FILTER      62464
#define IDS_ERR_BSTR2CHAR               62465
#define IDS_ERR_ERRLOGGER_EVENT         62466
#define IDS_ERR_ERRLOGGER_REGISTER      62467

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        301
#define _APS_NEXT_COMMAND_VALUE         33122
#define _APS_NEXT_CONTROL_VALUE         1350
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
