/*
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * \file      WebBrowser2.h
 * \brief     Interface file for CWebBrowser2 class
 * \author    Raja N
 * \copyright Copyright (c) 2011, Robert Bosch Engineering and Business Solutions. All rights reserved.
 *
 * Interface file for CWebBrowser2 class
 */


#if !defined(AFX_WEBBROWSER2_H__5510F817_9540_415A_955F_DA947F77AFBF__INCLUDED_)
#define AFX_WEBBROWSER2_H__5510F817_9540_415A_955F_DA947F77AFBF__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CWebBrowser2 wrapper class

class CWebBrowser2 : public CWnd
{
protected:
    DECLARE_DYNCREATE(CWebBrowser2)
public:
    CLSID const& GetClsid()
    {
        static CLSID const clsid
            = { 0x8856f961, 0x340a, 0x11d0, { 0xa9, 0x6b, 0x0, 0xc0, 0x4f, 0xd7, 0x5, 0xa2 } };
        return clsid;
    }
    virtual BOOL Create(LPCTSTR /*lpszClassName*/,
                        LPCTSTR lpszWindowName, DWORD dwStyle,
                        const RECT& rect,
                        CWnd* pParentWnd, UINT nID,
                        CCreateContext* /*pContext = NULL*/)
    {
        return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID);
    }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
                const RECT& rect, CWnd* pParentWnd, UINT nID,
                CFile* pPersist = NULL, BOOL bStorage = FALSE,
                BSTR bstrLicKey = NULL)
    {
        return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
                             pPersist, bStorage, bstrLicKey);
    }

    // Attributes
public:

    // Operations
public:
    void GoBack();
    void GoForward();
    void GoHome();
    void GoSearch();
    void Navigate(LPCTSTR URL, VARIANT* Flags, VARIANT* TargetFrameName, VARIANT* PostData, VARIANT* Headers);
    void Refresh();
    void Refresh2(VARIANT* Level);
    void Stop();
    LPDISPATCH GetApplication();
    LPDISPATCH GetParent();
    LPDISPATCH GetContainer();
    LPDISPATCH GetDocument();
    BOOL GetTopLevelContainer();
    CString GetType();
    long GetLeft();
    void SetLeft(long nNewValue);
    long GetTop();
    void SetTop(long nNewValue);
    long GetWidth();
    void SetWidth(long nNewValue);
    long GetHeight();
    void SetHeight(long nNewValue);
    CString GetLocationName();
    CString GetLocationURL();
    BOOL GetBusy();
    void Quit();
    void ClientToWindow(long* pcx, long* pcy);
    void PutProperty(LPCTSTR Property_, const VARIANT& vtValue);
    VARIANT GetProperty_(LPCTSTR Property_);
    CString GetName();
    long GetHwnd();
    CString GetFullName();
    CString GetPath();
    BOOL GetVisible();
    void SetVisible(BOOL bNewValue);
    BOOL GetStatusBar();
    void SetStatusBar(BOOL bNewValue);
    CString GetStatusText();
    void SetStatusText(LPCTSTR lpszNewValue);
    long GetToolBar();
    void SetToolBar(long nNewValue);
    BOOL GetMenuBar();
    void SetMenuBar(BOOL bNewValue);
    BOOL GetFullScreen();
    void SetFullScreen(BOOL bNewValue);
    void Navigate2(VARIANT* URL, VARIANT* Flags, VARIANT* TargetFrameName, VARIANT* PostData, VARIANT* Headers);
    long QueryStatusWB(long cmdID);
    void ExecWB(long cmdID, long cmdexecopt, VARIANT* pvaIn, VARIANT* pvaOut);
    void ShowBrowserBar(VARIANT* pvaClsid, VARIANT* pvarShow, VARIANT* pvarSize);
    long GetReadyState();
    BOOL GetOffline();
    void SetOffline(BOOL bNewValue);
    BOOL GetSilent();
    void SetSilent(BOOL bNewValue);
    BOOL GetRegisterAsBrowser();
    void SetRegisterAsBrowser(BOOL bNewValue);
    BOOL GetRegisterAsDropTarget();
    void SetRegisterAsDropTarget(BOOL bNewValue);
    BOOL GetTheaterMode();
    void SetTheaterMode(BOOL bNewValue);
    BOOL GetAddressBar();
    void SetAddressBar(BOOL bNewValue);
    BOOL GetResizable();
    void SetResizable(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_WEBBROWSER2_H__5510F817_9540_415A_955F_DA947F77AFBF__INCLUDED_)
