/* This file is generated by BUSMASTER */
/* VERSION [1.1] */
/* BUSMASTER VERSION [2.1.0] */
/* PROTOCOL [J1939] */

/* Start J1939 include header */
#include <Windows.h>
#include <J1939Includes.h>

/* End J1939 include header */


/* Start J1939 global variable */

/* End J1939 global variable */


/* Start J1939 Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnPGN_All(STJ1939_MSG* RxMsg);
GCC_EXTERN void GCC_EXPORT OnEvent_AddressClaim(BYTE byAddress);
/* End J1939 Function Prototype  */

/* Start J1939 generated function - OnPGN_All */
void OnPGN_All(STJ1939_MSG* RxMsg)
{

STJ1939_MSG msg;


msg.m_sMsgProperties.m_byChannel = 1;


msg.m_sMsgProperties.m_eType = MSG_TYPE_NM_ACL;

msg.m_sMsgProperties.m_eDirection = DIR_TX;


msg.m_sMsgProperties.m_uExtendedID.m_s29BitId.m_bySrcAddress = 0x00;


msg.m_sMsgProperties.m_uExtendedID.m_unExtID =0x1CEEFF00;

msg.m_sMsgProperties.m_uExtendedID.m_s29BitId.m_uPGN.m_sPGN.m_byPriority =0x6;

msg.m_unDLC = 8;

SendMsg (&msg);
}/* End J1939 generated function - OnPGN_All */
/* Start J1939 generated function - OnEvent_AddressClaim */
void OnEvent_AddressClaim(BYTE byAddress)
{
Trace("Address claimed");
}/* End J1939 generated function - OnEvent_AddressClaim */
