/* This file is generated by BUSMASTER */
/* VERSION [1.1] */
/* BUSMASTER VERSION [2.0.0] */
/* PROTOCOL [CAN] */

/* Start BUSMASTER include header */
#include <Windows.h>
#include <CANIncludes.h>

/* End BUSMASTER include header */


/* Start BUSMASTER global variable */

/* End BUSMASTER global variable */


/* Start BUSMASTER Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnKey_a(unsigned char KeyValue);
/* End BUSMASTER Function Prototype  */

/* Start BUSMASTER generated function - OnKey_a */
void OnKey_a(unsigned char KeyValue)
{
STCAN_MSG sMsg;

sMsg.m_unMsgID = 0x56;              // Message ID

sMsg.m_ucEXTENDED = FALSE;           // Standard Message type

sMsg.m_ucRTR = FALSE;                // Not RTR type

sMsg.m_ucDLC = 8;                    // Length is 8 Bytes

sMsg.m_sWhichBit.m_aulData[0] = 11;  // Lower 4 Bytes

sMsg.m_sWhichBit.m_aulData[1] = 22;  // Upper 4 Bytes

sMsg.m_ucChannel = 1;                // First CAN channel

SendMsg(sMsg);

Trace("Key Handler Node2");/* TODO */
}/* End BUSMASTER generated function - OnKey_a */
