/* This file is generated by BUSMASTER */
/* VERSION [1.1] */
/* BUSMASTER VERSION [2.6.4] */
/* PROTOCOL [LIN] */

/* Start LIN include header */
#include <Windows.h>
#include <LINIncludes.h>

/* End LIN include header */


/* Start LIN global variable */

/* End LIN global variable */


/* Start LIN Function Prototype  */
/* End LIN Function Prototype  */

/* Start LIN Function Wrapper Prototype  */
/* End LIN Function Wrapper Prototype  */


