/* This file is generated by BUSMASTER */
/* VERSION [1.2] */
/* BUSMASTER VERSION [2.6.4] */
/* PROTOCOL [LIN] */

/* Start LIN include header */
#include <Windows.h>
#include <LINIncludes.h>

/* End LIN include header */


/* Start LIN global variable */

/* End LIN global variable */


/* Start LIN Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnBus_Pre_Connect();
/* End LIN Function Prototype  */

/* Start LIN Function Wrapper Prototype  */
/* End LIN Function Wrapper Prototype  */


/* Start LIN generated function - OnBus_Pre_Connect */
void OnBus_Pre_Connect()
{
/* TODO */
STLIN_MSG sMsg1;

  sMsg1.messagetype = 1;                 // Slave Response
  sMsg1.checksumtype = 0;              // Classic
  sMsg1.dlc = 8;
  sMsg1.id = 0x8;                // Message Identifier
  sMsg1.data[1] = 10;  			// Lower 4 Bytes
  sMsg1.data[7] = 20;  			// Upper 4 Bytes
  sMsg1.cluster = 1;

  // Send the message
  SendMsg(sMsg1);

/* TODO */
STLIN_MSG sMsg2;

  sMsg2.messagetype= 1;                 // Slave Response
  sMsg2.checksumtype = 0;              // Classic
  sMsg2.dlc = 8;
  sMsg2.id = 0x10;                // Message Identifier
  sMsg2.data[1] = 10;  // Lower 4 Bytes
  sMsg2.data[7] = 20;  // Upper 4 Bytes
  sMsg2.cluster = 1;

  // Send the message
  SendMsg(sMsg2);
}/* End LIN generated function - OnBus_Pre_Connect */
