/* This file is generated by BUSMASTER */
/* VERSION [1.1] */
/* BUSMASTER VERSION [2.6.4] */
/* PROTOCOL [LIN] */

/* Start LIN include header */
#include <Windows.h>
#include <LINIncludes.h>
#include "C:\Module_AutomationV2\TestData\LINALTECM_01-00_Unions.h"

/* End LIN include header */


/* Start LIN global variable */

/* End LIN global variable */


/* Start LIN Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnBus_Pre_Connect();
/* End LIN Function Prototype  */

/* Start LIN Function Wrapper Prototype  */
/* End LIN Function Wrapper Prototype  */


/* Start LIN generated function - OnBus_Pre_Connect */
void OnBus_Pre_Connect()
{
/* TODO */

 ALT_LINALT_R_01 sMsgDB;

  sMsgDB.m_ucMsgTyp = 1; // Slave Response

  // Send the message
SendMsg(*((STLIN_MSG *)&sMsgDB));

ALT_LINALT_R_02 sMsgDB2;

 sMsgDB2.m_ucMsgTyp = 1; // Slave Response

  // Send the message
SendMsg(*((STLIN_MSG *)&sMsgDB2));
}/* End LIN generated function - OnBus_Pre_Connect */
