/* This file is generated by BUSMASTER */
/* VERSION [1.1] */
/* BUSMASTER VERSION [1.9.0] */
/* PROTOCOL [J1939] */

/* Start J1939 include header */
#include <Windows.h>
#include <J1939Includes.h>

#include "D:\Trunk_AutoIt\TestData\J1939DB_Unions.h"
/* End J1939 include header */


/* Start J1939 global variable */

/* End J1939 global variable */


/* Start J1939 Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnPGNName_Msg_Data(STJ1939_MSG* RxMsg);
/* End J1939 Function Prototype  */

/* Start J1939 generated function - OnPGNName_Msg_Data */
void OnPGNName_Msg_Data(STJ1939_MSG* RxMsg)
{
STJ1939_MSG msg1;


msg1.m_sMsgProperties.m_byChannel = 1;

msg1.m_sMsgProperties.m_eType = MSG_TYPE_DATA;

msg1.m_sMsgProperties.m_eDirection = DIR_TX;


msg1.m_sMsgProperties.m_uExtendedID.m_s29BitId.m_bySrcAddress = 30;
msg1.m_sMsgProperties.m_uExtendedID.m_unExtID =0x100;


msg1.m_unDLC = 8;

msg1.m_pbyData = new BYTE[15];
BYTE tmp[] = {12, 34, 45, 56, 78,11,44,55};

memcpy(msg1.m_pbyData, tmp, 8);

Trace("J1939 msg Handler1");

SendMsg (&msg1);


//msg2
STJ1939_MSG msg2;


msg2.m_sMsgProperties.m_byChannel = 1;

msg2.m_sMsgProperties.m_eType = MSG_TYPE_DATA;

msg2.m_sMsgProperties.m_eDirection = DIR_TX;


msg2.m_sMsgProperties.m_uExtendedID.m_s29BitId.m_bySrcAddress = 30;

msg2.m_sMsgProperties.m_uExtendedID.m_unExtID =0x200;


msg2.m_unDLC = 5;

msg2.m_pbyData = new BYTE[15];
BYTE tmp1[] = {13, 34, 45, 56, 78};

memcpy(msg2.m_pbyData, tmp1, 5);

Trace("J1939 msg Handler2");

SendMsg (&msg2);


//msg3

STJ1939_MSG msg3;


msg3.m_sMsgProperties.m_byChannel = 1;

msg3.m_sMsgProperties.m_eType = MSG_TYPE_DATA;

msg3.m_sMsgProperties.m_eDirection = DIR_TX;


msg3.m_sMsgProperties.m_uExtendedID.m_s29BitId.m_bySrcAddress = 30;
msg3.m_sMsgProperties.m_uExtendedID.m_unExtID =0x700;


msg3.m_unDLC = 5;

msg3.m_pbyData = new BYTE[15];
BYTE tmp2[] = {12, 35, 45, 56, 78};

memcpy(msg3.m_pbyData, tmp2, 5);

Trace("J1939 msg Handler3");

SendMsg (&msg3);

//msg4

STJ1939_MSG msg4;


msg4.m_sMsgProperties.m_byChannel = 1;

msg4.m_sMsgProperties.m_eType = MSG_TYPE_DATA;

msg4.m_sMsgProperties.m_eDirection = DIR_TX;


msg4.m_sMsgProperties.m_uExtendedID.m_s29BitId.m_bySrcAddress = 30;
msg4.m_sMsgProperties.m_uExtendedID.m_unExtID =0x800;



msg4.m_unDLC = 5;

msg4.m_pbyData = new BYTE[15];
BYTE tmp3[] = {12, 34, 46, 56, 78};

memcpy(msg4.m_pbyData, tmp3, 5);

Trace("J1939 msg Handler4");

SendMsg (&msg4);


//msg5

STJ1939_MSG msg5;


msg5.m_sMsgProperties.m_byChannel = 1;

msg5.m_sMsgProperties.m_eType = MSG_TYPE_DATA;

msg5.m_sMsgProperties.m_eDirection = DIR_TX;


msg5.m_sMsgProperties.m_uExtendedID.m_s29BitId.m_bySrcAddress = 30;
msg5.m_sMsgProperties.m_uExtendedID.m_unExtID =0x9b00;


msg5.m_unDLC = 5;

msg5.m_pbyData = new BYTE[15];
BYTE tmp4[] = {12, 34, 45, 57, 78};

memcpy(msg5.m_pbyData, tmp4, 5);

Trace("J1939 msg Handler5");

SendMsg (&msg5);




//msg6

STJ1939_MSG msg6;


msg6.m_sMsgProperties.m_byChannel = 1;

msg6.m_sMsgProperties.m_eType = MSG_TYPE_DATA;

msg6.m_sMsgProperties.m_eDirection = DIR_TX;


msg6.m_sMsgProperties.m_uExtendedID.m_s29BitId.m_bySrcAddress = 30;
msg6.m_sMsgProperties.m_uExtendedID.m_unExtID =0x9c00;


msg6.m_unDLC = 5;

msg6.m_pbyData = new BYTE[15];
BYTE tmp5[] = {12, 34, 45, 57, 78};

memcpy(msg6.m_pbyData, tmp5, 5);

Trace("J1939 msg Handler6");

SendMsg (&msg6);


//msg7

STJ1939_MSG msg7;


msg7.m_sMsgProperties.m_byChannel = 1;

msg7.m_sMsgProperties.m_eType = MSG_TYPE_DATA;

msg7.m_sMsgProperties.m_eDirection = DIR_TX;


msg7.m_sMsgProperties.m_uExtendedID.m_s29BitId.m_bySrcAddress = 30;
msg7.m_sMsgProperties.m_uExtendedID.m_unExtID =0x9d00;


msg7.m_unDLC = 5;

msg7.m_pbyData = new BYTE[15];
BYTE tmp6[] = {12, 36, 45, 56, 78};

memcpy(msg7.m_pbyData, tmp6, 5);

Trace("J1939 msg Handler7");

SendMsg (&msg7);


//msg8

STJ1939_MSG msg8;


msg8.m_sMsgProperties.m_byChannel = 1;

msg8.m_sMsgProperties.m_eType = MSG_TYPE_DATA;

msg8.m_sMsgProperties.m_eDirection = DIR_TX;


msg8.m_sMsgProperties.m_uExtendedID.m_s29BitId.m_bySrcAddress = 30;
msg8.m_sMsgProperties.m_uExtendedID.m_unExtID =0x9e00;


msg8.m_unDLC = 5;

msg8.m_pbyData = new BYTE[15];
BYTE tmp7[] = {12, 34, 47, 56, 78};

memcpy(msg8.m_pbyData, tmp7, 5);

Trace("J1939 msg Handler8");

SendMsg (&msg8);

//msg9

STJ1939_MSG msg9;


msg9.m_sMsgProperties.m_byChannel = 1;

msg9.m_sMsgProperties.m_eType = MSG_TYPE_DATA;

msg9.m_sMsgProperties.m_eDirection = DIR_TX;


msg9.m_sMsgProperties.m_uExtendedID.m_s29BitId.m_bySrcAddress = 30;
msg9.m_sMsgProperties.m_uExtendedID.m_unExtID =0x9f00;

msg9.m_unDLC = 5;

msg9.m_pbyData = new BYTE[15];
BYTE tmp8[] = {12, 34, 45, 58, 78};

memcpy(msg9.m_pbyData, tmp8, 5);

Trace("J1939 msg Handler9");

SendMsg (&msg9);




STJ1939_MSG msg10;


msg10.m_sMsgProperties.m_byChannel = 1;

msg10.m_sMsgProperties.m_eType = MSG_TYPE_DATA;

msg10.m_sMsgProperties.m_eDirection = DIR_TX;


msg10.m_sMsgProperties.m_uExtendedID.m_s29BitId.m_bySrcAddress = 30;
msg10.m_sMsgProperties.m_uExtendedID.m_unExtID =0xa100;



msg10.m_unDLC = 5;

msg10.m_pbyData = new BYTE[15];
BYTE tmp9[] = {12, 34, 45, 56, 80};

memcpy(msg10.m_pbyData, tmp9, 5);

Trace("J1939 msg Handler10");

SendMsg (&msg10);
}/* End J1939 generated function - OnPGNName_Msg_Data */
