/* This file is generated by BUSMASTER */
/* VERSION [1.1] */
/* BUSMASTER VERSION [1.9.0] */
/* PROTOCOL [CAN] */

/* Start BUSMASTER include header */
#include <Windows.h>
#include <CANIncludes.h>

#include "D:\Module AutomationV2\TestData\testNS_03_Unions.h"
/* End BUSMASTER include header */


/* Start BUSMASTER global variable */

/* End BUSMASTER global variable */


/* Start BUSMASTER Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnMsgName_Message1(Message1 RxMsg);
/* End BUSMASTER Function Prototype  */

/* Start BUSMASTER generated function - OnMsgName_Message1 */
void OnMsgName_Message1(Message1 RxMsg)
{
/* TODO */
}/* End BUSMASTER generated function - OnMsgName_Message1 */
