/* This file is generated by BUSMASTER */
/* VERSION [1.1] */
/* BUSMASTER VERSION [1.9.0] */
/* PROTOCOL [J1939] */

/* Start J1939 include header */
#include <Windows.h>
#include <J1939Includes.h>
#include "D:\Busmaster svn\BUSMASTER OSS\Tests\AutoIt\Module AutomationV2\TestData\J1939DB_Unions.h"

/* End J1939 include header */


/* Start J1939 global variable */

/* End J1939 global variable */


/* Start J1939 Function Prototype  */
/* End J1939 Function Prototype  */

