/* This file is generated by BUSMASTER */
/* VERSION [1.1] */
/* BUSMASTER VERSION [1.9.0] */
/* PROTOCOL [CAN] */

/* Start BUSMASTER include header */
#include <Windows.h>
#include <CANIncludes.h>

#include "D:\Trunk_AutoIt\TestData\testNS_03_Unions.h"
/* End BUSMASTER include header */


/* Start BUSMASTER global variable */

/* End BUSMASTER global variable */


/* Start BUSMASTER Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnMsgName_Message1(Message1 RxMsg);
/* End BUSMASTER Function Prototype  */

/* Start BUSMASTER generated function - OnMsgName_Message1 */
void OnMsgName_Message1(Message1 RxMsg)
{
//Msg1
STCAN_MSG sMsg;

sMsg.m_unMsgID = 0x101;              // Message ID

sMsg.m_ucEXTENDED = FALSE;           // Standard Message type

sMsg.m_ucRTR = FALSE;                // Not RTR type

sMsg.m_ucDLC = 8;                    // Length is 8 Bytes

sMsg.m_sWhichBit.m_aulData[0] = 10;  // Lower 4 Bytes

sMsg.m_sWhichBit.m_aulData[1] = 20;  // Upper 4 Bytes

sMsg.m_ucChannel = 1;                // First CAN channel

SendMsg(sMsg);

Trace("Msg Handler 1");

//Msg2
sMsg.m_unMsgID = 0x102;              // Message ID

sMsg.m_ucEXTENDED = FALSE;           // Standard Message type

sMsg.m_ucRTR = FALSE;                // Not RTR type

sMsg.m_ucDLC = 8;                    // Length is 8 Bytes

sMsg.m_sWhichBit.m_aulData[0] = 11;  // Lower 4 Bytes

sMsg.m_sWhichBit.m_aulData[1] = 21;  // Upper 4 Bytes

sMsg.m_ucChannel = 1;                // First CAN channel

SendMsg(sMsg);

Trace("Msg Handler 2");

//Msg3
sMsg.m_unMsgID = 0x103;              // Message ID

sMsg.m_ucEXTENDED = FALSE;           // Standard Message type

sMsg.m_ucRTR = FALSE;                // Not RTR type

sMsg.m_ucDLC = 8;                    // Length is 8 Bytes

sMsg.m_sWhichBit.m_aulData[0] = 12;  // Lower 4 Bytes

sMsg.m_sWhichBit.m_aulData[1] = 22;  // Upper 4 Bytes

sMsg.m_ucChannel = 1;                // First CAN channel

SendMsg(sMsg);

Trace("Msg Handler 3");

//Msg4
sMsg.m_unMsgID = 0x104;              // Message ID

sMsg.m_ucEXTENDED = FALSE;           // Standard Message type

sMsg.m_ucRTR = FALSE;                // Not RTR type

sMsg.m_ucDLC = 8;                    // Length is 8 Bytes

sMsg.m_sWhichBit.m_aulData[0] = 13;  // Lower 4 Bytes

sMsg.m_sWhichBit.m_aulData[1] = 23;  // Upper 4 Bytes

sMsg.m_ucChannel = 1;                // First CAN channel

SendMsg(sMsg);

Trace("Msg Handler 4");

//Msg5
sMsg.m_unMsgID = 0x105;              // Message ID

sMsg.m_ucEXTENDED = FALSE;           // Standard Message type

sMsg.m_ucRTR = FALSE;                // Not RTR type

sMsg.m_ucDLC = 8;                    // Length is 8 Bytes

sMsg.m_sWhichBit.m_aulData[0] = 14;  // Lower 4 Bytes

sMsg.m_sWhichBit.m_aulData[1] = 24;  // Upper 4 Bytes

sMsg.m_ucChannel = 1;                // First CAN channel

SendMsg(sMsg);

Trace("Msg Handler 5");

//Msg6
sMsg.m_unMsgID = 0x106;              // Message ID

sMsg.m_ucEXTENDED = FALSE;           // Standard Message type

sMsg.m_ucRTR = FALSE;                // Not RTR type

sMsg.m_ucDLC = 8;                    // Length is 8 Bytes

sMsg.m_sWhichBit.m_aulData[0] = 15;  // Lower 4 Bytes

sMsg.m_sWhichBit.m_aulData[1] = 25;  // Upper 4 Bytes

sMsg.m_ucChannel = 1;                // First CAN channel

SendMsg(sMsg);

Trace("Msg Handler 6");

//Msg7
sMsg.m_unMsgID = 0x107;              // Message ID

sMsg.m_ucEXTENDED = FALSE;           // Standard Message type

sMsg.m_ucRTR = FALSE;                // Not RTR type

sMsg.m_ucDLC = 8;                    // Length is 8 Bytes

sMsg.m_sWhichBit.m_aulData[0] = 16;  // Lower 4 Bytes

sMsg.m_sWhichBit.m_aulData[1] = 26;  // Upper 4 Bytes

sMsg.m_ucChannel = 1;                // First CAN channel

SendMsg(sMsg);

Trace("Msg Handler 7");

//Msg8
sMsg.m_unMsgID = 0x108;              // Message ID

sMsg.m_ucEXTENDED = FALSE;           // Standard Message type

sMsg.m_ucRTR = FALSE;                // Not RTR type

sMsg.m_ucDLC = 8;                    // Length is 8 Bytes

sMsg.m_sWhichBit.m_aulData[0] = 17;  // Lower 4 Bytes

sMsg.m_sWhichBit.m_aulData[1] = 27;  // Upper 4 Bytes

sMsg.m_ucChannel = 1;                // First CAN channel

SendMsg(sMsg);

Trace("Msg Handler 8");

//Msg9
sMsg.m_unMsgID = 0x109;              // Message ID

sMsg.m_ucEXTENDED = FALSE;           // Standard Message type

sMsg.m_ucRTR = FALSE;                // Not RTR type

sMsg.m_ucDLC = 8;                    // Length is 8 Bytes

sMsg.m_sWhichBit.m_aulData[0] = 18;  // Lower 4 Bytes

sMsg.m_sWhichBit.m_aulData[1] = 28;  // Upper 4 Bytes

sMsg.m_ucChannel = 1;                // First CAN channel

SendMsg(sMsg);

Trace("Msg Handler 9");

//Msg10
sMsg.m_unMsgID = 0x110;              // Message ID

sMsg.m_ucEXTENDED = FALSE;           // Standard Message type

sMsg.m_ucRTR = FALSE;                // Not RTR type

sMsg.m_ucDLC = 8;                    // Length is 8 Bytes

sMsg.m_sWhichBit.m_aulData[0] = 19;  // Lower 4 Bytes

sMsg.m_sWhichBit.m_aulData[1] = 29;  // Upper 4 Bytes

sMsg.m_ucChannel = 1;                // First CAN channel

SendMsg(sMsg);

Trace("Msg Handler 10");
}/* End BUSMASTER generated function - OnMsgName_Message1 */
