/* This file is generated by BUSMASTER */
/* VERSION [1.2] */
/* BUSMASTER VERSION [3.0.0] */
/* PROTOCOL [LIN] */

/* Start LIN include header */
#include <Windows.h>
#include <LINIncludes.h>
/* End LIN include header */


/* Start LIN global variable */

/* End LIN global variable */


/* Start LIN Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnDLL_Load();
GCC_EXTERN void GCC_EXPORT OnDLL_Unload();
GCC_EXTERN void GCC_EXPORT OnBus_Connect();
/* End LIN Function Prototype  */

/* Start LIN Function Wrapper Prototype  */
/* End LIN Function Wrapper Prototype  */


/* Start LIN generated function - OnDLL_Load */
void OnDLL_Load()
{
/* TODO */
Trace("Node1-Load");
}/* End LIN generated function - OnDLL_Load */
/* Start LIN generated function - OnDLL_Unload */
void OnDLL_Unload()
{
/* TODO */
Trace("Node1-Unload");
}/* End LIN generated function - OnDLL_Unload */
/* Start LIN generated function - OnBus_Connect */
void OnBus_Connect()
{
/* TODO */
Trace("Node1-Connect");
}/* End LIN generated function - OnBus_Connect */
