
#if !defined TYPECODE_FBX_ENTITIES_H__INCLUDED_
#define TYPECODE_FBX_ENTITIES_H__INCLUDED_

#define SIZE_NAME   128

#define VER_FBX_NONE        0x00
#define VER_FBX_1_2         0x01
#define VER_FBX_2_0_1       0x02
#define VER_FBX_3_0         0x03


enum eENTITY_FIBEX
{
    /* BASIC TYPE */
    TYPE_CNONE = 0,
    TYPE_CSTRING,
    TYPE_CSTRINGTOKEN,
    TYPE_CSTRINGARRAY,
    TYPE_CSTRINGTOKENLIST,
    TYPE_BOOL,
    TYPE_ULONG,
    TYPE_SHORT,
    TYPE_UINT,
    TYPE_INT,
    TYPE_FLOAT,
    TYPE_BYTE,
    TYPE_DOUBLE,
    TYPE_STRING_TOKEN,

    /* GENERAL */
    TYPE_CFIBEXENTITYDATA,
    TYPE_SADMIN_DATA,
    TYPE_SDOC_REVISION,
    TYPE_CDOCREVLIST,
    TYPE_SELEMENT_REVISION,
    TYPE_CELEMENTREVLIST,
    TYPE_SMODIFICATION,
    TYPE_CMODIFICATIONLIST,
    TYPE_SCOMPANY_REV_INFO,
    TYPE_CCOMPANYREVINFOLIST,
    TYPE_SNAMED_ELEMENT_TYPE,
    TYPE_SDECRIPTION,
    TYPE_STIME_RANGE,
    TYPE_UIDENTIFIER,


    /* ECU */
    TYPE_CECU,
    TYPE_SCONNECTOR,
    TYPE_CCONNECTORLIST ,
    TYPE_SPORT,
    TYPE_CPORTPDULIST,
    TYPE_SINCLUDED_PDU,
    TYPE_CINCLUDEDPDULIST,
    TYPE_SCONTROLLER,
    TYPE_CCONTROLLERLIST,
    TYPE_SDIAGNOSTIC_ADDRESSES,
    TYPE_STP_ADDRESS_REES,
    TYPE_CTPADDRESSLIST,
    TYPE_SFLEXRAY_SPECIFIC_CTRL,
    TYPE_SKEY_SLOT_USAGE,

    /* CLUSTER*/
    TYPE_CCLUSTER,
    TYPE_UBUSINFO,
    TYPE_SFLEXRAYCLUSTER,
    TYPE_SWAKEUP,

    /*CHANNEL*/
    TYPE_CCHANNEL,
    TYPE_SFRAME_TRIGGERING,
    TYPE_CFRAMETRIGGERINGLIST,
    TYPE_CFRAMETIMINGLIST,
    TYPE_STIMINGS,
    TYPE_SABSOLUTELY_SCHEDULED_TIMING,
    TYPE_UCYCLE,
    TYPE_SBASE_CYCLE,
    TYPE_SRELATIVELY_SCHEDULED_TIMING,
    TYPE_SPDU_TRIGGERING,
    TYPE_CPDU_TRIGGERINGLIST,
    TYPE_SPDUTRIGGTIMING,
    TYPE_CTIMINGLIST ,
    TYPE_SREQUEST_CONTROLLED_TIMING ,
    TYPE_SEVENT_CONTROLLED_TIMING ,
    TYPE_SCYCLIC_TIMING ,
    TYPE_SCONDITION ,
    TYPE_SSIGNAL_TRIGGER ,

    /*FRAME*/
    TYPE_CFRAME ,
    TYPE_SPDU_INSTANCE ,
    TYPE_CPDU_INSTANCELIST ,

    /*SIGNAL*/
    TYPE_CSIGNAL ,
    TYPE_SECU_SNDNG_BHVR ,
    TYPE_CECU_SNDNG_BHVRLIST ,
    TYPE_SSIGNAL_TYPE ,

    /*PDU*/
    TYPE_CPDU ,
    TYPE_SMULTIPLEXER ,
    TYPE_SSTATIC_PART ,
    TYPE_SSTATIC_PDU_INSTANCE ,
    TYPE_SDYNAMIC_PART ,
    TYPE_SSWITCHED_PDU_INSTANCE ,
    TYPE_CSWITCHPDUINSTLIST ,
    TYPE_SSEGMENT_POSITION ,
    TYPE_CSEGPOSLIST ,
    TYPE_SSWITCH ,
    TYPE_SSIGNAL_INSTANCE ,
    TYPE_CSIGINSTANCELIST ,
    TYPE_USIGNAL_START_POS ,
    TYPE_SSIGNAL_START_POS ,

    /*PROTOCOL*/
    TYPE_CPROTOCOL ,
    TYPE_CTPCONFIG ,
    TYPE_CTPCONFIGLIST ,
    TYPE_CCONFIGLIST ,

    /*FUNCTION*/
    TYPE_CFUNCTION ,
    TYPE_SFUNCTION_PORT_TYPE ,
    TYPE_CPORTLIST ,

    /*GATEWAY*/
    TYPE_CGATEWAY ,

    /*REQUIREMENT*/
    TYPE_CREQUIREMENT ,
    TYPE_SPDU_REQ ,
    TYPE_CPDUREQLIST ,
    TYPE_CSIGNALGROUP ,
    TYPE_CSIGNALGROUPLIST ,
    TYPE_SORDERED_SIGNAL ,
    TYPE_CORDEREDSIGNALLIST ,
    TYPE_SCOMMON_LAYOUT_DETAILS ,
    TYPE_SFUNCTION_REQ ,
    TYPE_CFUNCTIONREQLIST ,
    TYPE_SPORT_REQ ,
    TYPE_CPORTREQLIST ,
    TYPE_SPORT_REF ,
    TYPE_CPORTREFLIST ,

    /* PROCINFO*/
    TYPE_CPROCINFOMGR,
    /*UNIT_SPEC*/
    TYPE_CUNIT_SPEC ,
    TYPE_SUNIT ,
    TYPE_CUNITLIST ,
    TYPE_SUNITGROUP ,
    TYPE_CUNITGROUPLIST ,
    TYPE_SPHYSICAL_DIMENSION ,
    TYPE_CPHYSICALDIMENLIST ,

    /*CODING*/
    TYPE_CCODING,
    TYPE_SCODED_TYPE,
    TYPE_SLENGTH,
    TYPE_SMIN_MAX_LEN,
    TYPE_CMIN_MAXLIST,
    TYPE_SPHYSICAL_TYPE,
    TYPE_SCOMPU_METHOD,
    TYPE_CCOMPUMETHODLIST,
    TYPE_SCOMPU_INTERNAL_TO_PHYS,
    TYPE_SCOMPU_SCALE,
    TYPE_CCOMPUSCALELIST,
    TYPE_SCOMPU_RATIONAL_COEFFS,
    TYPE_SCOMPU_CONST,
    TYPE_SCONSTRS,
    TYPE_SLIMIT,

    /*COMPOSITE*/
    TYPE_CCOMPOSITE,
    /*FibexEntity*/
    TYPE_CFIBEXENTITY,

    /*ELEMENT*/
    TYPE_CELEMENT,

    /*PROCESSINFO*/

    /*CProjectData*/
    TYPE_CPROJECTDATA,
    TYPE_SFIBEX_COMPANY_DATA,
    TYPE_CFIBEXCODATALIST,
    TYPE_SPRODUCT,
    TYPE_CPRODUCTLIST,
    TYPE_SCOMPANY_DATA,
    TYPE_CCOMPANYDATALIST,
    TYPE_STEAM_MEMBER,
    TYPE_CTEAMMEMBERLIST,

    /* CFIBEXCONTAINER*/
    TYPE_CFIBEXCONTAINER,

    /* All the lists */
    TYPE_CCHANNELLIST,
    TYPE_CCLUSTERLIST,
    TYPE_CCOMPOSITELIST,
    TYPE_CECULIST,
    TYPE_CFRAMELIST,
    TYPE_CFUNCTIONLIST,
    TYPE_CGATEWAYLIST,
    TYPE_CPDULIST,
    TYPE_CCODINGLIST,
    TYPE_CPROJDATALIST,
    TYPE_CPROTOCOLLIST,
    TYPE_CSIGNALLIST,

    ENTITIES_TOTAL
};

#endif // TYPECODE_FBX_ENTITIES_H__INCLUDED_

