/*
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * \file      HashDefines.h
 * \brief     This header file contains the hash define
 * \authors   Amarnath Shastry, Amitesh Bharti, Krishnaswamy B.N
 * \copyright Copyright (c) 2011, Robert Bosch Engineering and Business Solutions. All rights reserved.
 *
 * This header file contains the hash define
 */

#pragma once

#define DEF_APPLICATION_VERSION     "BUSMASTER_Version"
#define DEF_LOG_BLOCK               "Log_Block"
#define DEF_IsEnabled               "IsEnabled"
#define DEF_TIME_MODE               "Time_Mode"
#define DEF_NUMERIC_MODE            "Numeric_Mode"
#define DEF_IS_APPEND_ENABLED       "IsAppendLog_Enabled"
#define DEF_RESET_ABS_TIME          "Reset_Absolute_Time"
#define DEF_CHANNEL                 "Channel"
#define DEF_FILE_PATH               "File_Path"
#define DEF_TRGR_STRT_ID            "Trigger_Start_ID"
#define DEF_TRGR_STP_ID             "Trigger_Stop_ID"
//#define DEF_FILTER                    "Filter"
#define DEF_CANFILTERS              "CAN_Filters"
#define DEF_MCNETFILTERS            "MCNET_Filters"
#define DEF_J1939FILTERS            "J1939_Filters"
#define DEF_FLEXRAYFILTERS          "FLEXRAY_Filters"
#define DEF_LINFILTERS              "LIN_Filters"
#define DEF_MOSTFILTERS             "MOST_Filters"
#define DEF_CAN_LOG                 "CAN_Log"
#define DEF_CAN_SIM_SYS             "CAN_Simulated_Systems"
#define DEF_J1939_SIM_SYS           "J1939_Simulated_Systems"
#define DEF_J1939_LOG               "J1939_Log"
#define DEF_FILTER                  "Filter"
#define DEF_NAME                    "Name"
#define DEF_TYPE                    "Type"
#define DEF_IDFROM                  "IdFrom"
#define DEF_IDTO                    "IdTo"
#define DEF_DIRECTION               "Direction"
#define DEF_IDTYPE                  "IDType"
#define DEF_MSGTYPE                 "MsgType"
#define DEF_CHANNEL                 "Channel"
#define DEF_APPEND                  "APPEND"
#define DEF_OVERWRITE               "OVERWRITE"
#define DEF_OVERWRITE_INTERPRETE    "OVERWRITE_INTERPRET"
#define DEF_FILTER_MESSAGE          "FilterMessage"
#define DEF_SIGNAL_WATCH            "CAN_Signal_Watch"
#define DEF_J1939_SIGNAL_WATCH      "J1939_Signal_Watch"
#define DEF_MESSAGE                 "Message"
#define DEF_NAME                    "Name"
#define DEF_SIGNAL                  "Signal"
//#define DEF_VISIBILITY                "Visibility"
#define DEF_WINDOW_POSITION         "Window_Position"
#define DEF_WINDOW_PLACEMENT        "WindowPlacement"
#define DEF_TOP                     "Top"
#define DEF_Left                    "Left"
#define DEF_Bottom                  "Bottom"
#define DEF_Right                   "Right"
#define DEF_Message_Column          "MESSAGE_COLUMN"
#define DEF_Columns_Width           "COLUMN_WIDTH"
#define DEF_Raw_Val_Column          "Raw_Val_Column"
#define DEF_Physical_Val_Column     "Physical_Val_Column"
#define DEF_Signal_Column           "Signal_Column"
#define DEF_CAN_SIGNAL_GRAPH        "CAN_Signal_Graph"
#define DEF_GRAPH_PARAMETERS        "GRAPH_PARAMETERS"
#define DEF_Buffer_Size             "Buffer_Size"
#define DEF_Refresh_Rate            "Refresh_Rate"
#define DEF_Frame_Color             "Frame_Color"
#define DEF_Frame_Style             "Frame_Style"
#define DEF_Plot_Area_Color         "Plot_Area_Color"
#define DEF_Grid_Color              "Grid_Color"
#define DEF_Axis_Color              "Axis_Color"
#define DEF_X_Grid_Lines            "X_Grid_Lines"
#define DEF_Y_Grid_Lines            "Y_Grid_Lines"
#define DEF_Active_Axis             "Active_Axis"
#define DEF_Selected_Action         "Selected_Action"
#define DEF_Show_Grid               "Show_Grid"
#define DEF_Display_Type            "Display_Type"
#define DEF_Graph_Element           "GRAPH_ELEMENT"
#define DEF_MESSAGE_ID              "Message_ID"
#define DEF_MESSAGE_NAME            "Message_Name"
#define DEF_FRAME_FORMAT            "Frame_Format"
#define DEF_ELEMENT_NAME            "Element_Name"
#define DEF_VALUE_TYPE              "Value_Type"
#define DEF_LINE_TYPE               "Line_Type"
#define DEF_LINE_COLOR              "Line_Color"
#define DEF_POINT_TYPE              "Point_Type"
#define DEF_POINT_COLOR             "Point_Color"
#define DEF_VISIBILITY              "Visibility"
#define DEF_ENABLE                  "Enable"
#define DEF_DISPLAY_TYPE            "Display_Type"
#define DEF_Splitter_Window_Col_0   "Splitter_Window_Col_0"
#define DEF_Splitter_Window_Col_1   "Splitter_Window_Col_1"
#define DEF_Splitter_Window_Row_0   "Splitter_Window_Row_0"
#define DEF_Splitter_Window_Row_1   "Splitter_Window_Row_1"
#define DEF_CX_IDEAL                "CxIdeal"
#define DEF_CX_MIN                  "CxMin"
#define DEF_CY_IDEAL                "CyIdeal"
#define DEF_CY_MIN                  "CyMin"
#define DEF_Global_Configuration        "Global_Configuration"
#define DEF_IsMsgFilterEnabled          "IsMsgFilterEnabled"
#define DEF_IsLogFilterEnabled          "IsLogFilterEnabled"
#define DEF_IsLoggingEnabled            "IsLoggingEnabled"
#define DEF_IsMsgIntepretationEnabled   "IsMsgIntepretationEnabled"
#define DEF_IsOverWriteEnabled          "IsOverWriteEnabled"
#define DEF_DisplayTimeMode             "DisplayTimeMode"
#define DEF_DisplayNumericMode          "DisplayNumericMode"
#define DEF_LogOnConnect_For_CAN        "LogOnConnect_CAN"
#define DEF_LogOnConnect_For_J1939      "LogOnConnect_J1939"
//Common defines
#define DEF_FILTER                  "Filter"
#define DEF_MSG_ID                  "ID"

#define DEF_MSGID                   "Id"
//TX window
#define DEF_CAN_TX_WINDOW           "CAN_Tx_Window"
#define DEF_MSG_BLOCK               "Message_Block"
#define DEF_BLOCK_NAME              "Block_Name"
#define DEF_MSG_ENABLED             "IsEnabled"
#define DEF_MSG_TRIGGER             "Trigger"
#define DEF_KEY_VAL                 "Key_Value"
#define DEF_TIME_INTERVAL           "Time_Interval"
#define DEF_MSG_IS_CYCLIC           "IsCyclic"
#define DEF_TRANSMIT_ALL_FRAMES     "Transmit_All_Frames"
#define DEF_MSGS                    "MESSAGES"
#define DEF_EXTENDED                "IsExtended"
#define DEF_RTR                     "IsRtr"
#define DEF_DLC                     "DLC"
#define DEF_CHANNEL                 "Channel"
#define DEF_DATABYTES               "DataBytes"
#define DEF_BYTE                    "Byte"
#define DEF_MSG_ENABLED             "IsEnabled"
#define DEF_AUTOSAVE                "IsAutoSaveEnabled"
#define DEF_SW_ROOT_0               "Splitter_Window_Root_0"
#define DEF_SW_ROOT_1               "Splitter_Window_Root_1"
#define DEF_SW_LEFT_0               "Splitter_Window_Left_0"
#define DEF_SW_LEFT_1               "Splitter_Window_Left_1"
#define DEF_SW_RIGHT_0              "Splitter_Window_Right_0"
#define DEF_SW_RIGHT_1              "Splitter_Window_Right_1"
#define DEF_CX_IDEAL                "CxIdeal"
#define DEF_CX_MIN                  "CxMin"
#define DEF_BLOCKS_TIME_ENABLED     "Time_Delay_Blocks_Enabled"
#define DEF_BLOCKS_TIME_DELAY       "Time_Delay_Blocks"

//Replay window
#define DEF_CAN_REPLAY              "CAN_Replay"
#define DEF_REPLAY                  "Replay"
#define DEF_LOG_PATH                "Log_File_Path"
#define DEF_ENABLED                 "IsEnabled"
#define DEF_RETAIN_RECORD_TIME      "Retain_Recored_Time"
#define DEF_MSG_DELAY               "Message_Delay"
#define DEF_CYCLIC_MODE             "Is_Cyclic_Mode"
#define DEF_CYCLIC_DELAY            "Cyclic_Delay"
#define DEF_INTERACTIVE             "IsInteractive"
#define DEF_REPLAY_MSG_DIRECTN      "Replay_Message_Direction"

//Message Window
#define DEF_MSG_WINDOW              "CAN_Message_Window"
#define DEF_MSG_ATTRIBUTE           "Message_Attribute"
#define DEF_NAME                    "Name"
#define DEF_MSG_COLOR               "Color"
#define DEF_COLUMN                  "COLUMN"
#define DEF_ID                      "ID"
#define DEF_MWND_ORDER              "Order"
#define DEF_MWND_COL_WIDTH          "Width"
#define DEF_MWND_ORDER              "Order"
#define DEF_IS_VISIBLE      "IsVisible"
#define DEF_MWND_HEX                "IsHex"
#define DEF_MWND_APPEND             "IsAppend"
#define DEF_MWND_INTERPRET          "IsInterpret"
#define DEF_MWND_TIME_MODE          "Time_Mode"
#define DEF_WND_POS                 "Window_Position"
#define DEF_VISIBILITY              "Visibility"
#define DEF_MWND_PLACEMENT          "WindowPlacement"
#define DEF_MWND_TOP                "Top"
#define DEF_MWND_LEFT               "Left"
#define DEF_BOTTOM                  "Bottom"
#define DEF_RIGHT                   "Right"
#define DEF_INTPRET_WND_POS         "Interpretation_Window_Position"
#define DEF_BOTTOM                  "Bottom"
#define DEF_RIGHT                   "Right"

#define DEF_J1939_MESS_WINDOW       "J1939_Message_Window"

#define DEF_SYS_PATH                "Sym_Path"

//TEST SUITE EDITOR
#define DEF_TS_XML_FILE_PATH        "XML_File_Path"
#define DEF_TS_EDITOR               "CAN_TS_Editor"
#define DEF_TREE_BKG_CLR            "Tree_Bkg_Color"
#define DEF_TREE_TXT_COLOR          "Tree_Text_Color"
#define DEF_LST_ROW1_CLR            "List_Row1_Color"
#define DEF_LST_ROW2_CLR            "List_Row2_Color"
#define DEF_ENABLE_AUTOSAVE         "EnableAutoSave"
#define DEF_SPLITTER_WINDOW         "Splitter_Window"

//Test suite executor
#define DEF_TS_EXECUTOR             "CAN_TS_Executor"
#define DEF_TS_NAME                 "Test_Suite_Name"
#define DEF_IS_ENABLE               "IsEnable"
#define DEF_TEST_SUITE              "TEST_SUITE"
#define DEF_FILE_PATH               "File_Path"
#define DEF_TEST_CASES_SEL          "Testcases_Selected"
#define DEF_INDEX                   "Index"

//Waveform generator
#define DEF_WF_GENERATOR            "CAN_Wave_Form_Genarator"
#define DEF_WAVE_FORM               "WAVE_FORM"
#define DEF_MSG_ID                  "Message_ID"
#define DEF_DEFAULT_AMPLITUDE       "Default_Amplitude"
#define DEF_WAVE_FORM               "WAVE_FORM"
#define DEF_SIGNALS                 "SIGNALS"
#define DEF_DEFAULT_AMPLITUDE       "Default_Amplitude"
#define DEF_WAVE_TYPE               "Wave_Type"
#define DEF_AMPLITUDE               "Amplitude"
#define DEF_FREQUENCY               "Frequency"
#define DEF_GRANULARITY             "Granularity"
#define DEF_DEF_SAMPLING_PERIOD     "Default_Sampling_Period"
#define DEF_SIGDEF_AUTOCORRECT      "SignalDefiner_AutoCorrect"

//Bus Statics
#define DEF_CAN_BUS_STATS           "CAN_Bus_Statistics"
#define DEF_COL_INFO                "COLUMSNINFO"
#define DEF_DEF_SAMPLING_PERIOD     "Default_Sampling_Period"

// Message Buffer Details
#define DEF_APPEND_BUFFER_SIZE      "Append_Buffer_Size"
#define DEF_OVERWRITE_BUFFER_SIZE   "Overwrite_Buffer_Size"
#define DEF_DISPLAY_UPDATE_TIME     "Display_Update_Time"
