//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TXWindow.rc
//
#define IDD_DLG_TX_MSG_DETAILS          102
#define IDD_DLG_TX_MSG_BLOCKS           103
#define IDD_DLG_SIGNAL                  131
#define IDD_DLG_TX_FUNCTIONS            132
#define IDR_BMP_MSGSGDB                 132
#define IDM_SEND_OPRNS                  164
#define IDM_CONFIG_MSG_BLOCK            165
#define IDR_BMP_MSG_SIG_WATCH           203
#define IDR_BMP_CHECKBOX                211
#define IDD_DLG_TX_MSG_BLOCK_DETAILS    281
#define IDC_EDIT_SGNAME                 1000
#define IDC_SPIN_SGLENGTH               1001
#define IDC_SPIN_BYINDEX                1002
#define IDC_EDIT_FACTOR                 1003
#define IDC_EDIT_UNIT                   1004
#define IDC_EDIT_MAX                    1005
#define IDC_EDIT_MIN                    1006
#define IDC_RADIOCYCLIC                 1007
#define IDC_SPIN_BIT                    1007
#define IDC_RADIOMONOSHOT               1008
#define IDC_COMB_SGTYPE                 1008
#define IDC_COMB_CHANNEL_ID             1010
#define IDC_COMBO_MSGS                  1010
#define IDC_BTN_UPDATE                  1014
#define IDC_BTN_CLOSE                   1015
#define IDC_STAT_SGNAME                 1019
#define IDC_STAT_BYINDEX                1020
#define IDC_STAT_STBIT                  1021
#define IDC_STAT_SGLEN                  1022
#define IDC_EDIT_BYINDEX                1023
#define IDC_EDIT_SGLEN                  1024
#define IDC_EDIT_STBIT                  1025
#define IDC_STAT_FACTOR                 1026
#define IDC_STAT_UNIT                   1027
#define IDC_STAT_MAX                    1028
#define IDC_STAT_MIN                    1029
#define IDC_STAT_TYPE                   1030
#define IDC_STAT_OFFSET                 1031
#define IDC_EDIT_OFFSET                 1032
#define IDC_STAT_8                      1057
#define IDC_STAT_7                      1065
#define IDC_STAT_6                      1066
#define IDC_STAT_5                      1067
#define IDC_STAT_4                      1073
#define IDC_STAT_3                      1074
#define IDC_STAT_2                      1075
#define IDC_STAT_1                      1076
#define IDC_STAT_9                      1084
#define IDC_STAT_10                     1085
#define IDC_STAT_11                     1086
#define IDC_STAT_12                     1087
#define IDC_STAT_13                     1088
#define IDC_STAT_14                     1089
#define IDC_LSTC_MSG_DETAILS            1099
#define IDC_CBTN_ADD_MSG                1122
#define IDC_STAT_HEADER2                1124
#define IDC_EDIT_DLC                    1125
#define IDC_EDIT_DB1                    1126
#define IDC_EDIT_DB2                    1127
#define IDC_EDIT_DB3                    1128
#define IDC_EDIT_DB4                    1129
#define IDC_EDIT_DB5                    1130
#define IDC_EDIT_DB6                    1131
#define IDC_EDIT_DB7                    1132
#define IDC_EDIT_DB8                    1133
#define IDC_EDIT_TRG_TIME_VAL           1134
#define IDC_EDIT_TRG_KEY_VAL            1137
#define IDC_STAT_UNIT_MS                1160
#define IDC_RBTN_MSGTYPE_EXTD           1213
#define IDC_RBTN_MSGTYPE_STD            1215
#define IDC_CHKB_MSGTYPE_RTR            1216
#define IDC_COMB_MSG_ID_NAME            1221
#define IDC_LSTC_MSG_BLOCKS_NAME        1225
#define IDC_CBTN_ADD_MSG_BLOCK          1226
#define IDC_CBTN_DELETE_MSG_BLOCK       1227
#define IDC_EDIT_MSG_BLOCK_NAME         1228
#define IDC_CBTN_SEND_MSG               1229
#define IDC_CBTN_DELETE_SEL_MSG         1230
#define IDC_CBTN_DELETE_ALL_MSG         1231
#define IDC_LSTC_SIG_DETAILS            1232
#define IDC_STAT_STATUS                 1233
#define IDC_CHKB_ON_TIME_TRIGGER        1236
#define IDC_CHKB_ON_KEY_TRIGGER         1237
#define IDC_STAT_161                    1247
#define IDC_STAT_151                    1248
#define IDC_STAT_MATRIX_RECT            1249
#define IDC_GROUPBOX_TRIGGER            1287
#define IDC_RADIO_INTEL                 1306
#define IDC_RADIO_MOTOROLA              1307
#define IDI_ICO_SEND                    17000
#define IDI_ICO_SEND_MSG                17000
#define IDM_ADD_MSG_BLOCK               32810
#define IDM_DELETE_SEL_MSG_BLOCK        32816
#define IDM_DELETE_SEL_MSG              32892
#define IDM_SEND_SEL_MSG                32897
#define IDM_DELETE_ALL_MSG              32944
